### ISSUE TITLE
How to pass arbitrary params to $http instance?

### ISSUE THREAD

**Issue by Dylan-Chapman** [robsontenorio/vue-api-query#11]
I have a global Axios error handler set up for all calls that use Axios. However, I want vue-api-query calls to handle their own errors. Normally I would handle turning off the global error handler for a specific call like this:
```javascript
this.$http.get( "/user/1", { handleErrors: false } )
```

But I don't see a way to add arbitrary params to the calls, only the pre-defined params like "include", "fields", etc. Maybe I'm just missing something?

Thanks for any help!

**Comment by prodigy7** [comment]
What a coincidence! I ask myself the same question, how I can handle errors directly with vue-api-query! Would be great if it is possible, handle errors cleanly directly with vue-api-query! +1 from me!
Important feature!

**Comment by robsontenorio** [comment]
Yes, a method to pass custom params on query is missing. I will do it ASP.

**Comment by robsontenorio** [comment]
Done! Just upgrade to 0.7.0

See README 
https://github.com/robsontenorio/vue-api-query#custom-params

**Comment by Dylan-Chapman** [comment]
Works perfectly! Thanks.
