### ISSUE TITLE
Add some flexibility

### ISSUE THREAD

**Issue by iMacTia** [robsontenorio/vue-api-query#110]
Hey, thanks for the repo!
I've just started using this library, having used similar ones for other languages, and I think it's great, however I noticed the overall direction is "we stick to the RESTful rules".
That basically means anything non-RESTful is basically impossible (if not with very complicated workarounds).

I was wondering if the team would be considering making this library a little more flexible because, let's face it, the world out there is not that simple and straightforward, and it would be a shame to loose users of this library because they can't do what they need.

In my particular case, I'm trying to do a simple POST request with some data to login the user.
The API I'm connecting to is mostly RESTful, but for `sign_in` they've decided to implement it as `auth/sign_in`. They're not changing that.

So I defined an Auth model and I was expecting to be able to do something like `Auth.custom('sign_in').post('email', 'password')`, but `post()` doesn't exist.

I already found #75 but that's clearly a hack...

Would the team be open to a PR implementing `post()`, `put()` and `delete()` for custom endpoints?

**Comment by robsontenorio** [comment]
Hi, 

This package follows "active record/model based" approach. So, for now this "random" post/put/delete methods would not make sense.

If you need to implement a very specific situation, i would advise you to use axios and you are done, once vue-api-query depends on it.


```
this.$axios.post({ ... })
```

**Comment by julianfox** [comment]
@iMacTia, thanks to the answer of @robsontenorio, I integrated custom actions like it:

`import Model from './model'

export default class Page extends Model {
  resource () {
    return 'pages'
  }

  primaryKey () {
    return 'uuid'
  }

  publish () {
    return this.request({
      method: 'PUT',
      url: `${this.endpoint()}/publish`
    }).then((response) => {
      const self = Object.assign(this, response.data)
      return self
    })
  }
}
`

According to the code source it's seems to be the best way to do it...

**Comment by iMacTia** [comment]
Thanks @julianfox, I never replied here but I did end up coding this myself as well.
I'll share my solution as well for future readers, in my case I first added a `post` method to my `Model` base class:

```js
post ({ path, data }) {
    let url = this.endpoint()
    if (path) {
      url += path
    }

    return this.request({
      method: 'POST',
      url: url,
      data: data
    }).then(response => {
      return Object.assign(this, response.data)
    })
  }
```

And then I use it where necessary in my models, like this (in this example, this is the `Auth` model):

```js
static signIn (email, password) {
    return this.instance().post({
      path: '/sign_in',
      data: {
        email,
        password
      }
    })
  }
```

This can be further generalised to create other methods in the `Model` class, like `.put()`, `.patch()` and so on...

**Comment by francoism90** [comment]
@julianfox @iMacTia Thanks for sharing your solutions. :)

**Comment by choxxy** [comment]
I keep getting this error while trying out  @iMacTia solution `TypeError: Converting circular structure to JSON --> starting at object with constructor 'User' | property '_builder' -> object with constructor 'Builder' --- property 'model' closes the circle`. Need help fixing this.
