### ISSUE TITLE
custom() not working properly

### ISSUE THREAD

**Issue by ronssij** [robsontenorio/vue-api-query#112]
assigning custom path to model is not working as it should.

> async saveWorkoutCircuitMultiple({ commit }, { workout, circuits }) {
           let _circuit = await new Circuit({ circuits }).custom('circuits/multiple').for(workout).save()
           return _circuit
    }

![image](https://user-images.githubusercontent.com/24932380/83018766-67f69180-a058-11ea-930d-679b28826bed.png)

**Comment by robsontenorio** [comment]
422 means `invalid data`, commonly validation errors on backend.

Try to post same payload on Postman or similar tool and see results.

**Comment by ronssij** [comment]
The issues is not the 422, the custom() is not using the custom request path. please look at the request endpoint. instead of having the `circuits/multiple` it on only using the `circuits`

**Comment by robsontenorio** [comment]
Maybe you can try latest example from this, once you have related models. 

https://github.com/robsontenorio/vue-api-query#define-your-domain-models

**Comment by ronssij** [comment]
Yes I did, I have that on my model. 

> {{API_URL}}/admin/workouts/:workout_id/circuits/multiple
This is my actual endpoint

> new Circuit({ circuits }).custom('circuits/multiple').for(workout).save()
this will supposedly work right ? since the custom() method allows to have the custom path.

**Comment by robsontenorio** [comment]
Some methods combinations does not work as expected.

You should try `custom()` without `for()` as described on README.

```
    let user = new User({ id: 1 })
    let post = new Post()

    // GET /users/1/posts/latest
    const result = await Post.custom(user, post, 'latest').get()
```
