### ISSUE TITLE
How we can do this nested query user/1/postes/5/tags

### ISSUE THREAD

**Issue by bnping** [robsontenorio/vue-api-query#113]
Can you help me pls in how to do this url :
user/1/postes/5/tags
I have the user, post and tag class.
thanks

**Comment by Peter-Krebs** [comment]
How relationships work is described under [Relationships](https://github.com/robsontenorio/vue-api-query#relationships) in the readme.

Then look for `.custom()` in the readme, regarding GET requests.
For PUT/POST requests, use `.for()` and then `.save()`.

Examples of them are also in the readme.

**Comment by Peter-Krebs** [comment]
@bnping Has my answer helped you? Can we close this issue?
