### ISSUE TITLE
orWhere

### ISSUE THREAD

**Issue by osqui** [robsontenorio/vue-api-query#114]
Hi,

Is there a way to add an 'orWhere' condition to the query? I have a free search field that can match either the 'title' or 'description' fields of the model.

By the way, thanks a lot for this great package!

**Comment by Peter-Krebs** [comment]
You should be able to use `params()` to do this ([readme: Custom params](https://github.com/robsontenorio/vue-api-query#custom-params)). Using example code here:  
```javascript
  // create the filter manually
  var filter = {};
  if (this.search.title.length) {
    filter.title = this.search.title;
  };
  if (this.search.description.length) {
    filter.description = this.search.description;
  }

  // in your call to a vue-api-query model ...
  .params({ filter: filter })
```

The `filter` param should be stringyfied for you if I'm not mistaken.

**Comment by Peter-Krebs** [comment]
If this is not what you mean, you should call `where()` as normal and let the backend just search in both fields anyway.

**Comment by osqui** [comment]
Thanks for your help! The thing is I don't have both 'title' and 'description' search fields, but a 'free search' one that should match either 'title' or 'description' columns.

However, I've solved it on server side with a scope filter:

`
    public function scopeTitleOrDescription(Builder $query, $str): Builder
    {
        return $query
            ->where('title', 'like', '%'.$str.'%')
            ->orWhere('description', 'like', '%'.$str.'%');
    }`

**Comment by osqui** [comment]
Thanks for your help! The thing is I don't have both 'title' and 'description' search fields, but a 'free search' one that should match either 'title' or 'description' columns.

However, I've solved it on server side with a scope filter in my model:


    public function scopeTitleOrDescription(Builder $query, $str): Builder
    {
        return $query
            ->where('title', 'like', '%'.$str.'%')
            ->orWhere('description', 'like', '%'.$str.'%');
    }

**Comment by robsontenorio** [comment]
You should solve this on backend. There is no extra work on this API call. 

This is a single param you can achieve with “params()” method on vue-api-query.
