### ISSUE TITLE
Avoid empty filters

### ISSUE THREAD

**Issue by dionysiosarvanitis** [robsontenorio/vue-api-query#117]
Hi,

It would be useful, if we could conditionally add filters. Right now, the filters are always present in the url even if they are empty.

**Comment by Peter-Krebs** [comment]
Maybe I don't use the most recent version, but I don't get any `filter` parameter.  
Are you calling `where()` without parameters somewhere? Please share some code.

**Comment by dionysiosarvanitis** [comment]
Yes, I'm calling where with empty parameters that way `Audit.where('attribute', filter)`. Because filter can be empty the result will be a url like that `/audits?filter[attribute]=`

**Comment by Peter-Krebs** [comment]
I believe this is correct for the filters to do so. In case you search for records with an empty `title`, for example.

**Comment by robsontenorio** [comment]
Although it could be a improvement in this package, I would advice you to handle that things o backend. Because you can’t “trust” in anything sent through APIs. 

See backend recommended library on README. it just ignores things aren’t allowed.

**Comment by dionysiosarvanitis** [comment]
Yes that's true. But what if we could do something like
```js
Model.when(filter, (query) => query.where('attribute', filter)).orderBy('name')
```

**Comment by dionysiosarvanitis** [comment]
> you can’t “trust” in anything sent through APIs.
>

Definitely! Mostly, I see this as a way to cleanup the url.

**Comment by robsontenorio** [comment]
Hi,

At this moment i am not planning  query clean up. If you need so, you can just extend save() or get() method or your base model and just clean up query, before calling parent save() or get() method.
