### ISSUE TITLE
Getting relation data in a single query

### ISSUE THREAD

**Issue by Jacq** [robsontenorio/vue-api-query#118]
Hi,

I have a setup similar to the one in the docs with a User hasMany Post relations.
When getting the user information sometimes I already return the Posts in a user.posts field
This user.posts array is received by the browser correctly but is internally replaced by the posts() function (vue api query hasMany function), is this usage of the hasMany possible?
I mean should the nested data be objects of Posts instead of a 'function posts() { .-... })' entity?
Cheers!

**Comment by Peter-Krebs** [comment]
Having the `hasMany` relation the same as the `include` name causes this, yes.  
You may change the `hasMany` functions to whatever you like. A workaround for you might be to name them uppercase (`function Posts() {}`).

Creating an object with mixed case names will separate them:
```javascript
// Console output: { posts: Array(0), Posts: ƒ }
{ posts: [], Posts: function() {} }
```
