### ISSUE TITLE
data: meta:

### ISSUE THREAD

**Issue by newsages** [robsontenorio/vue-api-query#119]
And for this ?
{
    "data": [
        {
            "object": "Clientapp",
            "class_name": "Clientapp",
       .......
    "meta": {
        "include": [
            "apptype",
            "users"
        ],
        "custom": [],
        "pagination": {
            "total": 15,
            "count": 15,
            "per_page": 15,
            "current_page": 1,
            "total_pages": 1,
            "links": {}
        }
    }

**Comment by robsontenorio** [comment]
Please, provide more details.

**Comment by francoism90** [comment]
@robsontenorio I think he needs to use `$find(..)`, `$get()`, `$first()`. This was also a bit confusing to me. :)
