### ISSUE TITLE
Importing doesn't work

### ISSUE THREAD

**Issue by francoism90** [robsontenorio/vue-api-query#126]
```
Failed to compile with 2 errors
This dependency was not found:

* vue-api-query in ./src/boot/axios.js, ./src/models/Model.js

To install it, you can run: npm install --save vue-api-query
```

```
import { Model } from 'vue-api-query'
import axios from 'axios'

[...]
```

Downgrading to `1.5.2` solves the issue.

**Comment by robsontenorio** [comment]
Maybe some problem when publishing on npm. Just tagged 1.6.1 . Please, try again.

**Comment by robsontenorio** [comment]
@JoaoPedroAS51 can you confirm?

**Comment by francoism90** [comment]
@robsontenorio Thanks, will try and report back. It works fine when building the package locally, seems to be indeed related to npm.

**Comment by francoism90** [comment]
@robsontenorio The same issue happens when upgrading to `v.1.7.0` using npm. Could you please take a look? :)

**Comment by robsontenorio** [comment]
@JoaoPedroAS51 some issue on npm building ?

**Comment by JoaoPedroAS51** [comment]
Hi @francoism90! Can you try `v1.7.1`?

**Comment by francoism90** [comment]
@robsontenorio @JoaoPedroAS51 Working again on v1.7.1, thanks for the quick fix! :)

**Comment by JoaoPedroAS51** [comment]
The publish process is automated now, so this issue should not happen again :)
