### ISSUE TITLE
API Documenation

### ISSUE THREAD

**Issue by mikeerickson** [robsontenorio/vue-api-query#128]
Interested in using this package, but curious of API documentation exists (which lists all the available query build methods).  I can read the source just fine, but curious if any formal documentation exists.

Also, is it possible to preflight the built query, without executing `get()` method?  

I am trying to get a feel for what does what so looking for a bit detail

**Comment by robsontenorio** [comment]
Yes, you can dynamically build a query object without call get() or find()

What is your concerns?

**Comment by Peter-Krebs** [comment]
The library builds request compatible with [spatie/laravel-query-builder](https://github.com/spatie/laravel-query-builder) (see vue-api-query readme at the top).
You can infer the possible query parameters from there.

**Comment by robsontenorio** [comment]
Please, check the new docs.
