### ISSUE TITLE
Returned array

### ISSUE THREAD

**Issue by ronssij** [robsontenorio/vue-api-query#129]
I have this request from the server.

![image](https://user-images.githubusercontent.com/24932380/95840722-1a649200-0d77-11eb-9417-6a93a4c11e37.png)

I have this to controll the fetched data.
![image](https://user-images.githubusercontent.com/24932380/95840752-23556380-0d77-11eb-9c13-a4a8a72d2554.png)

but when I log the data property. all email entries are looped inside.

![image](https://user-images.githubusercontent.com/24932380/95840913-54359880-0d77-11eb-9dc7-0bd66dbc9496.png)

**Comment by robsontenorio** [comment]
This package expect array of objects. Indeed , in your case, I don't know if it would be a supported case.
