### ISSUE TITLE
How to get a nested resource without getting the parent?

### ISSUE THREAD

**Issue by Dylan-Chapman** [robsontenorio/vue-api-query#13]
Say I want to get the posts for ID user 1, "/users/1/posts". However, I have no need to get the actual user object, "/users/1" first.  Is there a built-in way to do this? I didn't have luck trying to run ```User.find(1).posts().get()``` for example. Any other way to accomplish this without the unneeded API call?

**Comment by robsontenorio** [comment]
You can create new instances manually. See on README.

```js
let post = new Post()
post.id = 123

// or just pass as a payload

let post = new Post({id: 123})

// of course you can pass any other params
```
Then..

```js
// GET /posts/123/comments
let comments = post.comments().get()
```

Make sure `Post` and `Comment` extends from a `BaseModel`.

**Comment by Dylan-Chapman** [comment]
Awesome, thanks! This method seems to work with ```get``` but not ```find``` as far as I can tell, though? So, modeling off of your example, I have:

```javascript
const User = new User({id: 1})
const Post = await User.posts().find(2)
```

This fires "/posts/2" instead of "/users/1/posts/2".

**Comment by robsontenorio** [comment]
The `find()` method is suposed to be used with single resources. 

For nested resources you should always use `get()`. 

As described on README you can use another methods before `get()` on nested resources. 

```
await user.posts().where('id', 2).get()
```

**Comment by Dylan-Chapman** [comment]
Okie dok. Is there some philosophy behind the ```find()``` method not being able to be used with nested resources? I thought nested resources with multiple identifiers was a common REST API pattern?

**Comment by robsontenorio** [comment]
@Dylan-Chapman  Now you can do this

```js
const User = new User({id: 1})
const Post = await User.posts().find(2)
```
Just upgrade to `1.1.0`. Thanks  @vjoao for PR!
