### ISSUE TITLE
orderBy to accept array of strings instead

### ISSUE THREAD

**Issue by rancou** [robsontenorio/vue-api-query#140]
In the documents, it says:

`await Model.orderBy('-created_at', 'category_id')  `

is it possible to somehow pass an array of strings as the args?

**Comment by JoaoPedroAS51** [comment]
Hi @rancou! You can use the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax):

```js
await Model.orderBy(...myArray)
```
