### ISSUE TITLE
How filter (gt) great than or (lt) less than?

### ISSUE THREAD

**Issue by yurirnascimento** [robsontenorio/vue-api-query#15]
How filter (gt) great than or (lt) less than?

Like spatie/laravel-query-builder example.

```
$user = QueryBuilder::for($query)
    ->allowedIncludes('posts', 'permissions')
    ->where('score', '>', 42) **<< this**
    ->first();
```

Reading the code, this is not possible right now.

**Updated:**

Sure, we can create scoped filters, but, a lot of work for a Great/Less than only.

**Comment by robsontenorio** [comment]
Yes, indeed the same problem as #7. I will keep this open. If you have any solution, please submit a PR.

**Comment by bpuig** [comment]
That example you are quoting is not a filter, but an example for an existing query.
I think there is no chained method for that, spatie's laravel-query-builder specifies that any extra filter has to be made into a scope or custom filter:
See [Scope Filters section](https://github.com/spatie/laravel-query-builder#scope-filters)
See [Custom Filters section](https://github.com/spatie/laravel-query-builder#custom-filters)

I have not tested, but this would have to work if your `$query` is a User model class element.
This is the scoped approach:
In your **User model**
 ```
public function scopeScoreGreaterThan(Builder $query, $value): Builder
    {
        return $query->where('score', '>',  $value);
    }
```
And then in your **UserController**
```
$user = QueryBuilder::for($query)
    ->allowedIncludes('posts', 'permissions')
    ->allowedFilters(Filter::scope('score_greater_than'))
    ->first();
```

**Comment by robsontenorio** [comment]
@bpuig thanks for explanation. As, mentioned in another issue, by now, there is no default way to handle it.
