### ISSUE TITLE
Custom arguments seems to be missing from the docs

### ISSUE THREAD

**Issue by francoism90** [robsontenorio/vue-api-query#151]
I was browsing the new docs; it seems the following is missing in the Vue example and isn't stated anymore in the docs:
https://github.com/robsontenorio/vue-api-query/blob/master/tests/dummy/models/User.js

Maybe I'm browsing the wrong section(s)? Is it also possible to have some sort of `setter` in the model? :)

Thanks.

**Comment by JoaoPedroAS51** [comment]
Hi @francoism90! Thank your your report! I'll update the docs in the next few days :)

**Comment by JoaoPedroAS51** [comment]
@francoism90 
> Is it also possible to have some sort of setter in the model?

Yes, I believe it's possible.
