### ISSUE TITLE
[Question] : configuration : why not use constructor injection ? 

### ISSUE THREAD

**Issue by deka** [robsontenorio/vue-api-query#156]
Hi,
If i understand we need do this : 
```
import Model from './Model'

export default class User extends Model {
  // Set the resource route of the model
  resource() {
    return 'users'
  }
}
```
Why not something like ? 
```
import Model from './Model'

export default class User extends Model {
    constructor () {
        super({
            resource: `users`s
        })
    }
}
```

**Comment by Peter-Krebs** [comment]
Constructor injection looks less elegant to me.  
`resource()` just returns the resource to build the endpoint URL, there is currently no need for something fancy.

The resource will probably be the same constant string forever, so is there any benefit?

**Comment by ronssij** [comment]
@Peter-Krebs I agree. oddly a react like. a bit messy and additional line of codes.

**Comment by robsontenorio** [comment]
@deka i have tried you have suggested at past. But there was some problem on build/uglify/transpiling process.

I am not sure if we shoud change it for now. Thanks!
