### ISSUE TITLE
No apparent way to handle endpoints deeper than two models 

### ISSUE THREAD

**Issue by Indemnity83** [robsontenorio/vue-api-query#16]
Maybe I've missed it, but there doesn't seem to be any way to handle endpoints and relationships deeper than two models. For example, given that I have an `App`, `Build` & `Dependency` model where the endpoint to list all dependencies of a given build of a given app looks like this:

```
/app/34/build/112/dependencies
```

Is there anything planned, or that I missed to handle this endpoint?

**Comment by yurirnascimento** [comment]
Maybe you can use "includes" for this.

`/app/34/build?include=dependencies`

**Comment by Indemnity83** [comment]
Fair point, although I was just simplifying an example. There is still a full set of verbs for the dependencies too:

```
GET /app/34/build/112/dependencies
POST /app/34/build/112/dependencies
PUT/PATCH /app/34/build/112/dependencies/123
DELETE /app/34/build/112/dependencies/123
```

**Comment by robsontenorio** [comment]
@lukecurtis93 have you managed it?

**Comment by Peter-Krebs** [comment]
@lukecurtis93 Check the readme for `for()`. It takes multiple arguments now.  
`.for(user, post, comment).delete()` should work.

**Comment by lukecurtis93** [comment]
ah yes ok i understand now - cheers guys
