### ISSUE TITLE
save() return results

### ISSUE THREAD

**Issue by ronssij** [robsontenorio/vue-api-query#162]
Vue api query version.

`"vue-api-query": "^1.5.2",`

```
async saveWorkout({ commit }, params) {
      let data = await new Workout(params).save()

      console.log(data)
}
```
the save() does not return the actual results of the request it always returns the value of the model and plus the data of the request result.

![image](https://user-images.githubusercontent.com/24932380/102863807-11c2c300-446e-11eb-809a-68f3bdcd1f71.png)

**Comment by robsontenorio** [comment]
I think it is related to ES syntax, not this package. Try:

```js
      let data = await (new Workout(params)).save()
```
