### ISSUE TITLE
Documentation navigation: URLs for "On this page" go to the starting page instead of the respective section

### ISSUE THREAD

**Issue by Peter-Krebs** [robsontenorio/vue-api-query#165]
*To reproduce:* Visit for example [Relationship Operations](https://robsontenorio.github.io/vue-api-query/api/relationship-operations/).

*Expected behaviour:* Opening links for "On this page" in a new window (on the right in widescreen layout) should link to their respective sections in the documentation.  
Linking to specific headlines in the documentation is especially useful so we can send people to a specific section of a documentation page.

*What actually happens:* The navigation only works when left clicking. Opening the resulting URL in a new browser window leads back to the documentation's starting page. The underlying links are not working correctly.  
Additionally, hovering over a headline and clicking the `#` also links back to the documentation's starting page.

**Comment by JoaoPedroAS51** [comment]
Hi @Peter-Krebs! Yes, I'm aware of this issue. That is happening because the website domain is a subdirectory (/vue-api-query), because of Github Pages. I think a good idea would be reporting this issue in [nuxt/content repo](https://github.com/nuxt/content), which is the package I used for docs. Would you mind to open this issue there? It's related to `theme-docs`. Thanks in advance! :)

**Comment by Peter-Krebs** [comment]
If Nuxt is the problem here, I'll browse their issues first.  
Weird that linking to paragraphs was of nobody's concern there, maybe there is a basepath setting we need to set somewhere I'm guessing.

I'll report back as soon as I have time to do so. Thanks for the reply.

**Comment by Peter-Krebs** [comment]
I had a quick look. You can set a basedir property. See this answer on StackOverflow:

[Configure nuxt.js application to work in a subdirectory on a webserver](https://stackoverflow.com/a/50944870/10441671)

**Comment by JoaoPedroAS51** [comment]
@Peter-Krebs Yes, the base is already set in [nuxt.config.js](https://github.com/robsontenorio/vue-api-query/blob/dev/docs/nuxt.config.js) :)

**Comment by Peter-Krebs** [comment]
Check out the Nuxt documentation - it works there:  
https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#env  
You're directly sent to the `#env` headline instead of having to scroll down.

You probably also have to set `baseURL` as well, I'm guessing.

**Comment by JoaoPedroAS51** [comment]
Yeah, it's working there, but I think it's because they are not making the documentation separated from the website. Their nuxt app is not running in a subdir like ours.

**Comment by Peter-Krebs** [comment]
I currently don't have time to investigate more, but it must be a configuration issue, not a general issue with Nuxt.

I have found NuxtJS configuration docs, which are apparently hosted in a subdirectory `/docs/2.x/`:  
https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#base

The above link even scrolls you to the "Base" headline. Can't we look at their configuration and apply it to ours?

**Comment by JoaoPedroAS51** [comment]
@Peter-Krebs I found out that it's a known issue. See https://github.com/nuxt/content/issues/376#issuecomment-702193217

They have shown a temporary workaround, which seems to fix this issue, but may cause side effects.
```js
hooks: {
    'vue-renderer:ssr:templateParams': function(params) {
      params.HEAD = params.HEAD.replace('<base href="/vue-api-query/">', '')
    }
  }
```
