### ISSUE TITLE
validation errors on model.save()

### ISSUE THREAD

**Issue by DJafari** [robsontenorio/vue-api-query#18]
how can handle validation errors on `model.save()` from backend such as `laravel` ?

i think if this library has a utility for that, it's awesome

**Comment by robsontenorio** [comment]
There are my ways to validate data on client side. What exactly are you looking for?

**Comment by DJafari** [comment]
i know, but i want server side validation for security reason
i want something like vform : https://github.com/cretueusebiu/vform

**Comment by DJafari** [comment]
exaclty i want a way to prevent using try catch in each save place, i think it's better handle it automatically, something like :

```
let user = User.find(1);

await user.save();

// check for validation error for name field
user.errors.has('name');
```

**Comment by robsontenorio** [comment]
Yes, would be usefull when backend responds with validation errors (status 422). But, for any other errors thrown by backend a try/catch block  would be necessary. 

The `save()` operation on backend side can throw any kind of error :(

**Comment by DJafari** [comment]
yes you say right, but in 99% we don't need other errors, but in 100% we want show validation errors, because it is exists always

i hate repeat in codes :D

**Comment by DJafari** [comment]
sure i can do it with simple helper function, but i want improved this great library

**Comment by robsontenorio** [comment]
Please, don't hesitate submitting a PR.

**Comment by DJafari** [comment]
of course, i will open a PR

**Comment by MichMich** [comment]
Is there a solution for this? I agree with @DJafari that there needs to be some kind of simple way to catch validation errors.
