### ISSUE TITLE
Method Spoofing

### ISSUE THREAD

**Issue by ronssij** [robsontenorio/vue-api-query#180]
![image](https://user-images.githubusercontent.com/24932380/109582985-196fa980-7b3a-11eb-9ee6-4baf39849354.png)

Noticed that the base model's `_reqConfig` removes/ditiching private data on the payload.
so assigning `_method: 'put'` on the model is not possible when it is a very useful usecase on some upload form.

![image](https://user-images.githubusercontent.com/24932380/109583188-75d2c900-7b3a-11eb-9a42-42666a80a935.png)

![image](https://user-images.githubusercontent.com/24932380/109583257-94d15b00-7b3a-11eb-81ed-9b48910f6778.png)

**Comment by ronssij** [comment]
I created a workaround for this issue. 

![image](https://user-images.githubusercontent.com/24932380/112458484-cf27c400-8d97-11eb-8707-6c3d1ca59e3a.png)

**Comment by JoaoPedroAS51** [comment]
Hi @ronssij! I'm working on a solution for this in #185
