### ISSUE TITLE
[Feature Request] Support SSR Mode

### ISSUE THREAD

**Issue by yoelpc4** [robsontenorio/vue-api-query#182]
Hi @robsontenorio thanks for your work on this great package. 

I just building a fresh project with nuxt.js framework along with your package. 

Currently I can find a model from my api on nuxt asyncData method, but when it comes to save method vue api query can't save my model to my api. This issue can be solved temporarily by placed the request on created hook instead of asyncData method, this means not using SSR feature at all as stated on https://github.com/robsontenorio/vue-api-query/issues/57#issuecomment-472463209.

After reading [nuxt lifecycle docs](https://nuxtjs.org/docs/2.x/concepts/nuxt-lifecycle) I try to debugging the model on created hook, turns out the model from asyncData SSR is an instance of Model class but the model after [client side hydration](https://ssr.vuejs.org/guide/hydration.html) is a plain object, so that when I call save method on that model it can't worked as expected.

In the future do you have any plan to support SSR mode especially on nuxt.js framework?

**Comment by JoaoPedroAS51** [comment]
Hi @yoelpc4! Adding support for nuxt would be awesome! I did some research, but couldn't find a way to make it work natively. Do you have any ideas?

I added an example of a temporary workaround in [nuxt usage example](https://robsontenorio.github.io/vue-api-query/examples/nuxt). This way you can use SSR at least.

Basically, use computed property to reassign the model.

**Comment by yoelpc4** [comment]
@JoaoPedroAS51 This means for every models instance on data of component, we must have a single copy of models instance in computed of vue component. 

I wonder which one of these overcomes are more efficient to CPU & RAM usage, my approach to putting fetch data function call on created hook (this results fetch data function call twice on server & client side on SSR mode) vs your approach to prepare two model instance on data & computed (this results fetch data function call once on SSR mode)?

**Comment by JoaoPedroAS51** [comment]
Hey @yoelpc4! Sorry for taking so long to respond.

> I wonder which one of these overcomes are more efficient to CPU & RAM usage

I really don't know. I never tested this.

But now I think it's better to use `beforeMount` hook. Seems cleaner to me since we can override the original variable.
Both, computed property and before mount hook were suggested by a member of nuxt team. (https://github.com/nuxt/nuxt.js/issues/9294#issuecomment-840585015)

Using `beforeMount`:
```js
async asyncData() {
  const post = Post.find(1)

  return { post }
},

beforeMount() {
  if (!(this.post instanceof Post)) {
    this.post = new Post(this.post)
  }
}
```

Using computed property:
```js
async asyncData() {
  const _post = Post.find(1)

  return { _post }
},

computed: {
  post() {
    return this._post instanceof Post ? this._post : new Post(this._post)
  }
}
```

**Comment by yoelpc4** [comment]
Yeah whenever I try to get models from backend via fetch method I got warning on console

>  WARN  Cannot stringify arbitrary non-POJOs Model

It looks like vue hydration process wouldn't stringify object with function as you mention on the nuxt repo above, so that `beforeMount` or `computed` is the current working solution.

Anyway thanks for your help @JoaoPedroAS51
