### ISSUE TITLE
Support for belongsTo relationship

### ISSUE THREAD

**Issue by cioraneanu** [robsontenorio/vue-api-query#19]
Is there currently a way to support the inverse one-to-many relationship?
Ex. Post **belongs to** User.

My current need is to extract the User from a given Post id.

In JSON API spec this is represented as 
`GET /posts/1/user`

**Comment by robsontenorio** [comment]
This package does not parse JSON API spec **for responses**. It is just a simple query builder **for requests**.

If you like to work with full JSON API you can try this:

https://github.com/robsontenorio/vue-api-query#thanks

**Comment by cioraneanu** [comment]
I am talking about generating requests. 

From your documentation, the following call:
```
let posts = await user
  .posts()
  .get()

```
generates this request:
`// GET users/1/posts`


I am interested in generating this request:
`// GET posts/1/user`
I know I can do it with a .custom('url') call but I think support for a belongsTo relation would greatly improve flexibility.

**Comment by robsontenorio** [comment]
I got it. But it is necessary to map the reverse keys to parent model, once we dont parse relationthips paths through JSON API responses. If you can draft some kind of spec i can look after.
