### ISSUE TITLE
Model table name

### ISSUE THREAD

**Issue by lioneaglesolutions** [robsontenorio/vue-api-query#197]
When using models names that differ from the table name, there is no where to pass the table name to the query when selecting specific fields.

**Patient Model**
```js
export default class Patient extends Model {
    resource() {
        return 'patients';
    }
}
```

**Query**
```js
var { data, links, meta } = await Patient.page(this.options.page)
    .limit(this.options.itemsPerPage)
    .orderBy(this.sortByWithDirection)
    .select('id', 'name')
    .get();
```

**Request Output**
`/patients?fields[patients]=id,name&page[number]=1&page[size]=25`

But in the database in Laravel this model actually uses the `users` table, as does another model `Practitioner`. So we need a way to customise the table name - not just the resource name. The request that works is;
`/patients?fields[users]=id,name&page[number]=1&page[size]=25`

**Controller**
```php
public function index(Request $request)
{
    $patients = QueryBuilder::for(Patient::class)->allowedSelects(['id', 'name'])->jsonPaginate();

    return PatientResource::collection($patients);
}
```

**Comment by JoaoPedroAS51** [comment]
Hi @lioneaglesolutions! Sorry for taking so long to respond. You can change the table name by passing an object to `select` method.

```js
Patient.select({
  users: ['id', 'name']
}).get()
```

Let me know if it worked :)
