### ISSUE TITLE
improvement: allow for specifying which columns should be retrieved

### ISSUE THREAD

**Issue by dasraab** [robsontenorio/vue-api-query#2]
see https://github.com/spatie/laravel-query-builder#selecting-specific-columns

maybe with api like this

`.include('relation', [columns])`

or if you dont want to change your current methods maybe smth like this:

`.onlyColumns('relation', [columns])`

would be a very useful addition 👍

**Comment by robsontenorio** [comment]
I`m considering something like this for single entity:

```js
// GET posts?fields[posts]=title,content

let post = await Post
   .select(['title', 'content'])
   .get() // find(), first()
```

With related entities:

```js
// GET posts?include=user&fields[posts]=title,content&fields[user]=firstname,age

let post = await Post
   .select({
      posts: ['title', 'content'],
      user: ['age', 'firstname']
    })
   .include('user')
   .get() // find() first()
```

**Comment by robsontenorio** [comment]
Update to 0.4.0

https://github.com/robsontenorio/vue-api-query/releases/tag/0.4.0
