### ISSUE TITLE
Cannot execute query PUT entity/{id}/collection/{itemid}

### ISSUE THREAD

**Issue by RobDixonIII** [robsontenorio/vue-api-query#207]
I've been trying to use the following technique to update a collection item:
![sync-documentation](https://user-images.githubusercontent.com/1163024/123439582-21db6c80-d58f-11eb-8bd3-03be8273521a.png)

I follow the example, but in the language of the example classes I get 'post.comments is not a function' even though I've set up relationships as described and even define the function on the model class.

My specific case involves music artists (like, bands) and artist members.  I've documented it here: https://github.com/planettelex/Songtracker-Pro/issues/58

**Comment by Peter-Krebs** [comment]
Hi!

The `post.comments is not a function` message certainly doesn't lie, this is a JavaScript error message. It can also mean that the `find()` call returned null, for example. Just to be sure, you can find documentation for it here:  
https://robsontenorio.github.io/vue-api-query/api/model-options#hasmany

In any case, you probably want to use `for()`, which is used for saving models. `PUT`/`POST` is chosen automatically, depending if the id in your model is set.  
https://robsontenorio.github.io/vue-api-query/performing-operations#creating-related-models

**Comment by JoaoPedroAS51** [comment]
Hi @RobDixonIII! I looked at the models in your repo and I believe this is happening because your eager and lasy loaded relationships have the same name. You must change the lazy loaded relation name for something else, so they stop conflicting.

```js
export default class Artist extends Model {
    resource() {
        return 'artists';
      }

      members() { // <-- You must rename this one
        return this.hasMany(ArtistMember);
      }

      managers() {
        return this.hasMany(ArtistManager);
      }

      accounts() {
        return this.hasMany(ArtistAccount);
      }

      relations() {
        return {
          'accounts': ArtistAccount,
          'members': ArtistMember,  // <-- It's conflicting with this one
          'managers': ArtistManager
        }
      }
}
```

@Peter-Krebs Good point. Indeed, `for` could be used here. We should add this approach to docs as well, since there's only "creating model" example :)

I think both approaches should work the same way. It's just a matter of preference.

**Comment by RobDixonIII** [comment]
Actually, I added both together just as a demo before committing.  I tried both independently and neither worked.

**Comment by RobDixonIII** [comment]
Yes, that worked!  The following pattern worked for collection POST, PUT, and DELETE. First of all, I ditched the relations method (although it didn't seem to cause any problems) so the model class looks like:
```javascript
import Model from './Model';
import ArtistMember from './ArtistMember';
import ArtistManager from './ArtistManager';
import ArtistAccount from './ArtistAccount';

export default class Artist extends Model {
    resource() {
        return 'artists';
      }

      members() {
        return this.hasMany(ArtistMember);
      }

      managers() {
        return this.hasMany(ArtistManager);
      }

      accounts() {
        return this.hasMany(ArtistAccount);
      }
}
```
The collection model classes look like:
```javascript
import Model from './Model';

export default class ArtistAccount extends Model {
    resource() {
        return 'accounts';
      }
}
```
Then I used the _for_ method in conjunction with _save()_ or _delete()_ methods.  _save()_ will POST or PUT depending on whether the object has an id or not.  As an added wrinkle, I need to include security headers in every API request, plus I have error handling. The end result looks like:
```javascript
const artistModel = await ArtistModel.config(this.RequestHeaders).find(this.editedArtist.id)
 .catch(error => this.handleError(error));
const artistAccountModel = new ArtistAccountModel(this.editedArtistAccount).config(this.RequestHeaders).for(artistModel);
await artistAccountModel.save()
 .then (() => {
    // Do post save stuff.
  })
  .catch(error => this.handleError(error));
```

Thanks guys! The above pattern is how I'll continue to use sub collections in the API.  It a pretty robust use case, feel free to use it in examples/documentation.
