### ISSUE TITLE
problem with version 1.9.1: Circular reference

### ISSUE THREAD

**Issue by luffynando** [robsontenorio/vue-api-query#211]
Converting circular structure to JSON --> starting at object with constructor 'User' | property '_builder' -> object with constructor 'Builder' --- property 'model' closes the circle.

Previous version: 1.9.0 ---> All works good
Current version: 1.9.1 ---> on save model throw Converting circular structure to JSON.

Partial fix downgrade to previous version.

**Comment by Peter-Krebs** [comment]
Can you add source code which causes this?  
This package uses automated tests - it would be a surprise to me if the circular reference is a general problem. Or maybe a test needs to be added to battle this issue.

**Comment by hoangnhiho** [comment]
I have the same issue.

```
import Model from "./Model";

export default class ContractDeduction extends Model {
    resource() {
        return "contract_deductions"
    }
}
```
I was on v1.9.0 
ended up downgrading to v1.8.2

**Comment by thelfensdrfer** [comment]
The problem in my code was that I used properties `funds!: Fund[]` instead of relationships. So the internal `_model` property caused an error: `TypeError: cyclic object value`

**Comment by luffynando** [comment]
> The problem in my code was that I used properties `funds!: Fund[]` instead of relationships. So the internal `_model` property caused an error: `TypeError: cyclic object value`

i confirm i used only declaration property and not add relationship
