### ISSUE TITLE
Adding offset as an additional default parameterNames.

### ISSUE THREAD

**Issue by ramsane** [robsontenorio/vue-api-query#212]
For pagination, we have page and limit as parameter names. But limit offset pagination is also something most people use. It would be nice to have this as one of the parameterNames.

**Comment by Peter-Krebs** [comment]
This not only affects parameter names, the package has dedicated functions as well (`.page()`, `.imit()`, [see pagination docs](https://robsontenorio.github.io/vue-api-query/building-the-query/#paginating)).

The JSON:API spec has several ideas [how to do pagination](https://jsonapi.org/format/#fetching-pagination) (number/size, offset/limit, cursor). Should all of those be functions and parameters as well?

As for now, you can always set parameters manually in a model query:
```javascript
  // Assuming we have a pagination object in data or equivalent...:
  .params({
    "page[size]": this.pagination.rowsPerPage,
    "page[number]": this.pagination.page
  })
  .get()
  .then(async response => {
    // ...
  });
```

**Comment by ramsane** [comment]
Understood. Closing this issue now.
