### ISSUE TITLE
How to use with typescript

### ISSUE THREAD

**Issue by dominicbachmann** [robsontenorio/vue-api-query#217]
How can I actually type a model (provide the properties it will have on the model itself)?  As soon as I add e.g. a name property on my Post-Model class the name will be of undefined value.

**Comment by luffynando** [comment]
The way I managed to model the responses was like this: 
```ts
import Model from './Model';

interface Permission {
    id: number;
    name: string;
    guard_name: string;
}

class Permission extends Model {
    public resource(): string {
        return 'permissions';
    }
}

export default Permission;
```
