### ISSUE TITLE
Any way to access the resource() field?

### ISSUE THREAD

**Issue by cioraneanu** [robsontenorio/vue-api-query#22]
I am trying to create a Repository class that receives a Model class in its constructor.
Is there any way to get the resource() string from a Model class?

**Comment by robsontenorio** [comment]
What do you mean?

Every model should implement a resource() method, that returns a string. 

So, `someModel.resource()` is the guy.

**Comment by cioraneanu** [comment]
Given a class Post, i was trying to get the resource String that I implemented via:
`Post.resource()` just like I called things other methods like`Post.find(x)`

Just saw that a working solution is:
`new Post().resource()`

Is this the right approach for getting the implemented method?

Thank you

**Comment by robsontenorio** [comment]
The `resource()` method will return something like `/users`, as declared on your models. 

If you wanna get the full generated uri like ’/users?filter[status]=active&...` you should look for builder methods on source code.
