### ISSUE TITLE
Model defaults/Model override documentation suggestion

### ISSUE THREAD

**Issue by miloandco** [robsontenorio/vue-api-query#222]
I think it could help a lot of people if you added some details to the docs, regarding setting model defaults/override Model base class.

For example, I needed a way to define some default fields on my models, which then be overridden through the select() method in my components. 

I solved it like seen below, hopefully, this can help others:

**Base model (Model.js)**
```javascript
import { Model as BaseModel } from 'vue-api-query'

export default class Model extends BaseModel {
	constructor(...attributes) {
		attributes.length ? super(...attributes) : super()

		if (this._builder && this.defaultFields().length) {
			this._builder.select(...this.defaultFields())
		}
	}

	defaultFields() {
		return []
	}
}
```

**Foobar.js**
```javascript
import Model from '@/models/Model'

export default class Foobar extends Model {
	defaultFields() {
		return ['id', 'firstName', 'lastName']
	}
}
```

->  _?fields[foobar]=id,firstName,lastName_

**Yet you can still use the select() method:**
`Foobar.select(['id', 'email'])`
 ->  _?fields[foobar]=id,email_

**Comment by ajcastro** [comment]
This seems related to this, #223 .

**Comment by miloandco** [comment]
> This seems related to or duplicate #223 . I should have just commented here. But I didn't see this first. Anyway this is how I did it myself:
> 
> ```js
> export default class Model extends BaseModel {
>   constructor(...attributes) {
>     super()
> 
>     if (attributes.length) {
>       Object.assign(this, this.defaultAttributes(), ...attributes)
>     }
>   }
> 
>   defaultAttributes() {
>     return {}
>   }
> }
> 
> 
> export default class User extends Model {
>   defaultAttributes() {
>     return {
>       selected: false // useful for checkbox or selection state
>     }
>   }
> }
> ```

I think your use case is different. You are looking into defining some default values for attributes on the model, where my example refers to which fields you are requesting from your API, using spaties query builder.

**Comment by ajcastro** [comment]
I see, thanks for the clarification 😇
