### ISSUE TITLE
Any way to delete multiple items at once in model?

### ISSUE THREAD

**Issue by narrative1st** [robsontenorio/vue-api-query#23]
Thanks for making this - works great. Though, I have a question about sending DELETE on a collection. I can get it well here:

```
     Model.where('id', payload.id)
        .get()
        .then(response => {
          modelItems = response;
          modelItems.delete();
        });
```

`modelItems` loads up with the right information. But the `destroy` method isn't working. Using Laravel for backend and I have this for `destroy()` method:

```
    public function destroy($ids)
    {
        $model = model::whereIn('id', $ids)->delete();
    }
```

**Comment by narrative1st** [comment]
Please feel free to close this issue - I didn't understand the concept of cascading deletes, which really has nothing to do with this great package you put up. My apologies for wasting your time.

**Comment by robsontenorio** [comment]
You got the point about “delete”.
