### ISSUE TITLE
[Question] Is the project still maintained and support for Vue 3?

### ISSUE THREAD

**Issue by ThaDaVos** [robsontenorio/vue-api-query#233]
Two questions:

1. Is the project still maintained? Seeing as the last commit was July 9, 2021
2. If it is, when will Vue 3 support land?

**Comment by arthur-er** [comment]
By looking at the dependencies, I think the package is framework-agnostic, so you can use it with any vue version

**Comment by robsontenorio** [comment]
Yes, at this pony is agnostic.
