### ISSUE TITLE
model.patch does not change the method to PATCH

### ISSUE THREAD

**Issue by jawadashraf** [robsontenorio/vue-api-query#246]
Hi,
I am using https://github.com/laravel-json-api/laravel for the jsonapi backend and 
I am new to this library, having some issues with patch method.
user.patch() does not change the method to PATCH, it remains POST and does not change url and keeps it
api/v1/users.

I am reporting this after I checked config in BaseModel request method.
`request(config) {
    return this.$http.request(config)
  }`

If I get user model using 
`model = await User.$find(1)` then model.patch() works but since the sent attributes are unwrapped, laravel jsonapi backend sends error because it does not receive member data.

Thanks

**Comment by JoaoPedroAS51** [comment]
Hi @jawadashraf! Can you show me how you are making the request? I think all you need is to set the ID before making the request.

**Comment by jawadashraf** [comment]
@JoaoPedroAS51 thanks for the response. I am calling it like this `model = await User.$find(1)`
and then after modifying a property I am calling `model.patch()`. Anyway, I found a way to pass the data back in compliance with jsonapi standards.
