### ISSUE TITLE
Nuxt 3 support ?

### ISSUE THREAD

**Issue by Aurion72** [robsontenorio/vue-api-query#247]
There is a nuxt 3 support from this package ?

**Comment by robsontenorio** [comment]
Right now it is framework agnostic.

**Comment by codeturn** [comment]
But, it dont work with nuxt3. 
I get error:" [ERROR] Could not resolve "@babel/runtime/helpers/interopRequireDefault".."
Can you update nuxt example for nuxt 3?
Thank you!

**Comment by kszyrvercobrador** [comment]
If anyone have same issue with @codeturn, try install @babel/runtime. It works on my end
`npm i -D @babel/runtime`
