### ISSUE TITLE
how to get success when I do update or create 

### ISSUE THREAD

**Issue by AlejandroBonilla** [robsontenorio/vue-api-query#25]
Hi robsontenorio , thanks for your library , I've been using it  in a new project . I have a problem when I save a model, how can I get status=200 or success for doing redirections, I'm using laravel-query-builder in my backend.

`async sendData(){
        let proveedor= await ProveedorModel.find(this.rutProvider)
        proveedor.razon_social =this.nameProvider
        proveedor.save()
			}`
I would like to redirect when save is successfully .

**Comment by robsontenorio** [comment]
You are talking about ES6, not vue-api-query. 

Just wrap your code with “try/catch”. So your redirect can be placed on “try” block. On “catch” block you can throw a fancy error message, um case of failure.
