### ISSUE TITLE
X-CSRF-TOKEN header

### ISSUE THREAD

**Issue by jrogelj** [robsontenorio/vue-api-query#26]
How to add custom X-CSRF-TOKEN header to specific requests? I manged to add it when declaring base model, but I was not able to read and dynamically change the CSRF token value from the Vuex store or local storage. Is it possible to add custom headers when making specific request?

**Comment by robsontenorio** [comment]
I think you could achieve that by setting axios headers property, once you (probably) are mixing Laravel blade content with Vuejs components.

**Comment by jrogelj** [comment]
I imported store into Base model and than I was able to access data saved in the Vuex store. Now it works fine.

**Comment by robsontenorio** [comment]
Maybe you can share your example to solve this issue #24
