### ISSUE TITLE
Override resource() for current model instance and make it available for usage with save() / delete()

### ISSUE THREAD

**Issue by Peter-Krebs** [robsontenorio/vue-api-query#27]
The current readme informs about `.custom()`, for use with GET requests: [readme - Define your domain models](https://github.com/robsontenorio/vue-api-query/tree/master#define-your-domain-models)  
`.custom()` is currently not meant to work outside of GET, is this correct? Using it for `save()` as well is a use-case we would be interested in.

`new Example({name:'example'}).custom('alternative/resource').save()`
As of version 1.1.0, the above will send a POST request to `/Example` instead of `alternative/resource`.

Is this absolutely intended? Or could the `.custom()` feature be made so `.save()` respects it as well?
This could also be a workaround for #16

**Comment by robsontenorio** [comment]
@Peter-Krebs Yes, `custom()` is intended to set a temporary resource url for getting data.  This package respects the Model instance when using `save()` and `delete()`, because the resource already was defined on it. The REST API should be consistent.

The issue #16 requires other context not covered by this package.

**Comment by Peter-Krebs** [comment]
@robsontenorio Having `/zoo/1/cage/2/animal/3` would be consistent as well.  

Using `.custom()` is a possible workaround right now for GET requests.  
Using `.save(...).for()` can only build two hierarchy levels in total: the current model and one parent model. Correct?

An API cannot be used consistently if it uses 3 hierarchy levels currently, because saving is not possible. Is this generally considered a _bad_ API design, having 3 hierarchy levels?  
Needing `zoo/1/cage/2` and `cage/2/animal/3` seemed a bit redundant to us.

**Comment by robsontenorio** [comment]
@Peter-Krebs Your proposal for `custom()` would be changing resource url for the current Model instance overriding the default one? 

If so, this is a breaking change, because `custom()` has been used for other scenario. In this case a new method must be implemented on `vue-api-query` to achieve that behavior. Are you able to send a PR?

**Comment by Peter-Krebs** [comment]
We could offer to put some time in as soon as we can, sure.  

From a usage standpoint we would like this behaviour:  
**Loading**  
```
// GET /zoos/1
let zoo = await Zoo.find(1)

// GET /zoos/1/cages/2
let cage = await zoo.cage().find(2)

// GET /zoos/1/cages/2/animals
let animals = await cage.animal().get()

// GET /zoos/1/cages/2/animals/3
let animal = await cage.animal().find(3)
```

**Saving**  
```
let zoo = new Zoo({id: 1})
let cage = new Cage({id: 2})

let animal = new Animal({title:"Tiger"}).for(cage).for(zoo)

// POST /zoos/1/cages/2/animals
animal.save()
```

**Comment by Indemnity83** [comment]
Syntax suggestion on the saving example:

```js
let zoo = new Zoo({id: 1})
let cage = new Cage({id: 2})

let animal = new Animal({title:"Tiger"}).for(cage, zoo)
```

Remove the explict argument list on the for() function and make use of the arguments object so multiple Models can be sent in a single function. Could just be syntax sugar with a recursive check at the start of the function, or just wrap the whole logic in a for loop, whatever makes the most sense. 

```js
for () {
  arguments.forEach(object => {
    // do function
  }
}
```

**Comment by Peter-Krebs** [comment]
@Indemnity83 Thanks for the suggestion.  
I've gotten around to implement `for()` with arguments locally, also updated tests and the readme.

I just need some time for a re-think and then testing what I've implemented. Soon™
