### ISSUE TITLE
Get specific object by other field than id

### ISSUE THREAD

**Issue by melokki** [robsontenorio/vue-api-query#3]
Hello, nice package.

One question I have, how can I call the following route? `/cities/bucharest/` `bucharest` beeing a slug in my table.

I want to query the api with the slug not with the id and the `find` method won't work in this case. The `custom` method could be a solution for this, but I'll have to do something like this `City.custom('cities/' + slug).first()` and it's not that pretty

There could be other solution or should I just stick with the custom method approach?

**Comment by robsontenorio** [comment]
@melokki 

By "default" REST API would not handle `/cities/<slug>`. The `custom()` method cover that case.

You can even chain more methods from `vue-api-query`:

```js
  City
     .custom('cities/' + slug)
     .include(...)
     .first()
```

And it will return a instance of `City` model.

**Comment by melokki** [comment]
Thank you for your answer @robsontenorio 

Can we maybe include a `show` method that would be similar with `find` but will not test to see if the parameter is integer?
I'll try to write a PR if you agree with this.

**Comment by robsontenorio** [comment]
I agree with you. Will be fixed in next hours.

**Comment by robsontenorio** [comment]
Update to 0.4.0

https://github.com/robsontenorio/vue-api-query/releases/tag/0.4.0

**Comment by melokki** [comment]
Works like a charm, thank you very much @robsontenorio 

I don't really understand your above question.

**Comment by robsontenorio** [comment]
Just try to get a register by slug and after save it (city.save)

--
Robson Tenório 

Em 5 de abr de 2018, à(s) 17:53, melokki <notifications@github.com> escreveu:
