### ISSUE TITLE
Version 1.1.1 hasn't reached npm/yarn

### ISSUE THREAD

**Issue by prodigy7** [robsontenorio/vue-api-query#30]
Hi there!

I try to install version 1.1.1 with patch from peter (https://github.com/robsontenorio/vue-api-query/commit/967f7901bf7fbcecb318795b4070398cb79c198d) but i get only the response, that 1.1.1 isn't available. I've checked npm and yarn, both has still version 1.1.0.
Can you please submit the version to both repositories?

Thank you!

**Comment by robsontenorio** [comment]
Done!
