### ISSUE TITLE
Q: Query parameter name customisation

### ISSUE THREAD

**Issue by PrimozRome** [robsontenorio/vue-api-query#32]
Maybe I have missed it somehow but reading trough your docs I haven't found that you can customise how the parameters are named when sent to the back-end. For example if not working with Spatie ORM package.

Here are my two questions.

1. Can I customise how `vue-query-api` generates URL and names parameters? From your docs

```
// GET /posts?filter[status]=ACTIVE&include=user,category&append=likes&orderBy=-created_at,category_id

let posts = await Post
  .where('status', 'ACTIVE')
  .include('user', 'category')
  .append('likes')
  .orderBy('-created_at', 'category_id')  
  .get()
```

For example if I would like that `filter[status]` is named `filter_by[status]` for example. 

2. Can I customise how array parameters are encoded in the URL? For example here is filter by array which in your documentation says its send like this:

```
//GET /posts?filter[status]=ACTIVE,ARCHIVED

let posts = await Post
  .whereIn('status', ['ACTIVE', 'ARCHIVED'])
  .get()

```

I wonder if it's possible to send like this:

`//GET /posts?filter[status][]=ACTIVE&filter[status][]=ARCHIVED`

Thank you.

**Comment by robsontenorio** [comment]
#### 1. Can I customise how vue-query-api generates URL and names parameters?

Yes, you can name params and values  as you wish

```js
// GET /posts?filter[my_fancy_status]=ACTIVE_ONE

let posts = await Post
  .where('my_fancy_status', 'ACTIVE_ONE')
  .get()
```

#### 2. Can I customise how array parameters are encoded in the URL? For example here is filter by array which in your documentation says its send like this:

According to `spatie/laravel-query-builder` docs, you can perform a "AND" or "OR". Both are supported by `vue-api-query`.
So if you intend to use `vue-api-query` and `spatie/laravel-query-builder` you must stick to the convention. 


You can also pass in an array of filters to the allowedFilters() method.
```php
// GET /users?filter[name]=john&filter[email]=gmail
$users = QueryBuilder::for(User::class)
    ->allowedFilters(['name', 'email'])
    ->get();
// $users will contain all users with "john" in their name AND "gmail" in their email address
```

```php
// GET /users?filter[name]=seb,freek
$users = QueryBuilder::for(User::class)
    ->allowedFilters('name')
    ->get();
// $users will contain all users that contain "seb" OR "freek" in their name
```

**Comment by PrimozRome** [comment]
@robsontenorio you didn't get my answer right for the point 1.

I want to customise the **filter** in `filter[status]` not the status field name...

**Comment by robsontenorio** [comment]
@PrimozRome I'm sorry, but right now it is not possible, because is sticked to the convention

**Comment by PrimozRome** [comment]
I think it would be an useful add-on, having some-kind of configuration possibility to rename default key names. Really not a big deal I guess.

**Comment by PrimozRome** [comment]
UPDATE:

` spatie/laravel-query-builder` package also allows to change these parameters so I think this is needed to reflect the configuration on the server side.

```
return [

    /*
     * By default the package will use the `include`, `filter`, `sort` and `fields` query parameters.
     *
     * Here you can customize those names.
     */
    'parameters' => [
        'include' => 'include',

        'filter' => 'filter',

        'sort' => 'sort',

        'fields' => 'fields',
    ],

];

```

**Comment by robsontenorio** [comment]
For now, lets stick to default. If you can, please submit a PR.

**Comment by robsontenorio** [comment]
Now that is possible 
https://github.com/robsontenorio/vue-api-query/pull/42
