### ISSUE TITLE
Q: what is the difference between include and append

### ISSUE THREAD

**Issue by PrimozRome** [robsontenorio/vue-api-query#33]
I am trying to figure out what append does? I get the include, but not sure what append does. From the docs:

Give me the result for a given criteria, include some entities, append extra fields and order the result!

```
// GET /posts?filter[status]=ACTIVE&include=user,category&append=likes&orderBy=-created_at,category_id

let posts = await Post
  .where('status', 'ACTIVE')
  .include('user', 'category')
  .append('likes')
  .orderBy('-created_at', 'category_id')  
  .get()

```

**Comment by robsontenorio** [comment]
By convention, 

include = relationships 
https://github.com/spatie/laravel-query-builder#including-relationships

append = "computed" attributes
https://github.com/spatie/laravel-query-builder#append-attributes
