### ISSUE TITLE
Custom Request Header

### ISSUE THREAD

**Issue by saeidee** [robsontenorio/vue-api-query#34]
Thanks for the nice package, but I think still we need to append some custom header with the request for example if we need to send form data with the request like binary files so we need to set the **Content-Type** header to **multipart/form-data** or even if we need some other custom headers like **X-ApplicationId** or etc.
It would be nicer if you add a function for this feature like bellow! 

`let user = new User(data, headers);
user.save();`

Thanks

**Comment by saeidee** [comment]
Yes, you are right but it will be nice if we have a function like headers() to set custom headers.
otherwise, we should override functions in all Models.
like this: 
```javascript 
 _create () {
    return this.request({
	method: 'POST',
	url: this.endpoint(),
	data: this,
        headers: this.headers()
    }).then(response => {
	let self = Object.assign(this, response.data)
	return self
    })
}
```
By the way there is a problem in parseing **FormData** Object as you are destructuring it in Model constractor it is makes it empty!
```javascript 
 constructor(...atributtes) {}
```
Could you please check it with FormData Object!

**Comment by saeidee** [comment]
Not this!
As I told you problem is about destructuring FormData.
````javascript
Array.from(formData.entries()).reduce((o, [k, v]) => {
    o[k] = v;
    return o;
}, {}); 
````
This code will return object but still we will have problem with binaray data!

**Comment by robsontenorio** [comment]
Binary data = file upload?

If so, I don’t know if package can help you. Sorry.
