### ISSUE TITLE
Q: How do I add properties to `this` on models correctly?

### ISSUE THREAD

**Issue by Peter-Krebs** [robsontenorio/vue-api-query#36]
I had trouble defining custom properties on the models, maybe you have a 
best-practice approach for me on this, as my current fix is a workaround.

I went and added a custom property to my base class for vue-js-api models 
(I have a getter and setter as well):

`MyModelBase.js`
```js
  constructor(...args) {
    super(args);
    
    this._myProp = "";
    
    return this;
  }
```

Initializing a Model with the constructor resulted in exceptions in the browser console.

`page.vue`
```js
  // This throws an error in the console, that `.include()` is not a function
  await MyModel
    .include(['test'])
    .first()
    .then( response => () {} )
    
    ...
```

I realised later that adding the constructor did something bad.  
Consider your Model's constructor: 

`Model.js`  
```js
  constructor(...atributtes) {
    super()

    if (atributtes.length === 0) {
      this._builder = new Builder(this)
    } else {
      Object.assign(this, ...atributtes)
    }
    
    ...
  }
```

The else portion there skips initializing `this._builder` - probably because you assume
it is of on of your Models and already has a `_builder`. But in this case it's called
from my custom constructor.

I fixed adding _builder in the constructor of my base class, which
is of course not future-proof. It currently works for my use-cases.

```js
    // Added after the call to super()
    this._builder = new Builder(this);
```

*Q:* Am I adding the custom constructor incorrectly? Is there an alternative 
way to add properties to `this`?

> PS: The correct spelling is `attributes`, not `atributtes`.  
> Is this intentional? Or is this an ES6 thing where attributes is a reserved word?  
> Maybe you are handling an unknown number of butts with atritis?  
> In that case it should be atriButts :)

Edit: Formatting

**Comment by robsontenorio** [comment]
I don’t have `this` on ES6 class. 

And yes, `atributtes` is a typo (I am not fluent in English, haha)

Can you paste your entire base model?

**Comment by robsontenorio** [comment]
I mean you don’t return this

**Comment by Peter-Krebs** [comment]
No, I return `this`. See the first code (MyModelBase.js), this is what my constructor looks like.  
The Model.js constructor is the one from vue-api-query - the `...` just means I left out the rest of the function.

I have a handful of resources which are available at different endpoints. I was creating a property that lets me switch between baseURLs:
```js
import { Model as BaseModel } from 'vue-api-query'
import Builder from 'vue-api-query/src/Builder'

export default class Model extends BaseModel {

    constructor(...args) {
      super(args);
      
      this._builder = new Builder(this);
      this._baseUrlPrefix = "";
      
      return this;
    }

    // define a base url for a REST API
    baseURL() {
        return Vue.axios.defaults.baseURL.replace(/\/$/, "") + this.baseUrlPrefix;
    }

    // implement a default request method
    request(config) {
        return this.$http.request(config)
    }

    // The baseUrlPrefix must begin with a /, unless it is empty.
    // We handle this here.
    get baseUrlPrefix() {
      
      // Automagically add / at the beginning.
      if( this._baseUrlPrefix.length > 0 && this._baseUrlPrefix.charAt(0) !== '/' ) {
        return '/' + this._baseUrlPrefix;
      }
      else {
        return this._baseUrlPrefix;
      }
    }

    // Direct access to the property. You may want to use
    // setBaseUrlPrefix() so calls are chainable.
    set baseUrlPrefix(prefix) {
      
      if( typeof prefix !== 'string' ) {
        throw new Error('prefix must be of type "string".')
      }

      this._baseUrlPrefix = prefix;
    }

    // Define a base URL prefix for this model.
    // Supply a prefix, for example setBaseUrlPrefix("profile").
    // Returns this so you can chain this call with other functions.
    setBaseUrlPrefix(prefix) {
      this.baseUrlPrefix = prefix;
      return this;
    }
}
```

**Comment by Peter-Krebs** [comment]
I now had time to test my base model by fetching actual data.  
It seems adding the constructor is currently not the way to go. Fetching data will put the data one level below the model somehow, whatever the reason maybe.

`Fetched data in the model object (before adding constructor)`
```js
  {
    id: 0,
    text: "Hello."
  }
```

`Fetched data in the model object (after adding constructor)`
```js
  {
    [0] => {
      id: 0,
      text: "Hello."
    }
  }
```

I'm sure this is because I'm using inheritance incorrectly, at least for this library.  
But how do I add custom properties to the model then?

**Comment by robsontenorio** [comment]
@Peter-Krebs Probably you are trying querying with in a new created objected. The issue with current implementation of vue-api-query is when create a new object, is supposed to place a .save() afterwards.

```
let user = new User({name: 'Joe', age: 26})

// what is supposed to do next? 
user.save()
```

The builders method will work for the static object, the query mechanism

```
import User from '@/models/user'
...

let user = User.find(1)

let users = User.includes('city').orderby('id').get()


```

**Comment by Peter-Krebs** [comment]
No the problem is also there for GET requests. I'm trying to make this work:

```js
// setBaseUrlPrefix() chains together nicely
// //localhost/friends/users?include=pants
await User
  .include(['pants'])
  .setBaseUrlPrefix('friends')
  .first()
  .then(response => { /*...*/ });

// This should also work with an instance as well
// //localhost/friends/users
var user = new User({name:'joe'});
user.setBaseUrlPrefix('friends')
  .save()
  .then(response => { /*...*/ });
```

But adding my own constructor and the `this._baseUrlPrefix` property fetches the data incorrectly ([see comment above](https://github.com/robsontenorio/vue-api-query/issues/36#issuecomment-441041205)).
This may also not work with `save()`, since the `_baseUrlPrefix` property might be added to the request as well. I haven't continued debugging since what I'm doing is not the correct way.

And nevermind my examples. How would I add something like a custom property and methods to the models? Or do I have to implement this kind of thing somewhere else?

Thanks for your time!

**Comment by robsontenorio** [comment]
Here is the BaseModel you are looking for

```
import { Model as BaseModel } from 'vue-api-query'

export default class Model extends BaseModel {

  constructor(...attributes) {
    attributes.length ? super(...attributes) : super()

    this.myVar = 123
  }

  // define a base url for a REST API
  baseURL () {
    return process.env.API_URL
  }

  // implement a default request method
  request (config) {
    return this.$http.request(config)
  }
}
```

**Comment by Peter-Krebs** [comment]
Ok I'll give it a shot, thanks!  
I will be on vacation for two weeks so we will get in touch after.

**Comment by Peter-Krebs** [comment]
Ah yes, `return this` in the constructor is incorrect.  
This works for me, thank you!
