### ISSUE TITLE
inlciude on .find()

### ISSUE THREAD

**Issue by PrimozRome** [robsontenorio/vue-api-query#38]
```
// GET /posts/1

let post = await Post.find(1)
```

This wont let me chain include() function. Any particular reason why this would not work or be possible? I want to have possibility to include relations here or not.

**Comment by robsontenorio** [comment]
find() and get() works with chained method. Share your query and the error. 

Here is a example:


https://github.com/robsontenorio/vue-api-query/blob/master/README.md#relationships

**Comment by PrimozRome** [comment]
@robsontenorio I am trying to do something like this:

`let users = User.include('profile', 'address').find(1)`

but include is not appended to the request url
