### ISSUE TITLE
Callbacks that get called before and after requests?

### ISSUE THREAD

**Issue by Scarwolf** [robsontenorio/vue-api-query#47]
Hi,

First of all, as someone who was pretty new in the Vue game and previously used ugly axios calls in every component, this makes everything much prettier, so thanks for that!

Now, I was wondering, is there a possibility to use callbacks like `beforeRequest` & `afterRequest` or something that you can either define in the Base Model.js or in any of the Submodels?

Some background to understand my use case:
I am using https://www.npmjs.com/package/vue-loading-overlay which basically draws a Loading spinner over the entire screen while a specific variable is set to `true`. 

While it works perfectly fine like this:
```
        async mounted() {
           /*
           * Fetches all Services
           */
          this.$parent.isLoading = true;
          this.services = await Service.get();
          this.$parent.isLoading = false;
        },
```

It would be much prettier with callbacks defined in the models.

Thanks!

**Comment by robsontenorio** [comment]
@Scarwolf This would be a new feature, like injecting loading state into Models. PR are welcome ;)

**Comment by Scarwolf** [comment]
Sadly my Javascript skills aren't good enough to contribute on a project like this so I hope someone else might implement this :)

**Comment by ZeroThe2nd** [comment]
In addition: Callbacks would also be the perfect place to add some persistence logic. `beforeFetch` and `afterFetch` being perfect places to load or persist data from/to a local storage system.

While definitely not the most elegant, you can still do something like this in your model:
```javascript
export default class User extends BaseModel {
  resource () {
    return 'user'
  }

  beforeFetch() {
    // do things pre-fetch
  }

  postFetch() {
    // do things after fetch
  }

  get () {
    this.beforeFetch()

    const result = super.get()

    this.postFetch()

    return result
  }
}
```
