### ISSUE TITLE
Can not use keyword 'await' outside an async function

### ISSUE THREAD

**Issue by bernhardh** [robsontenorio/vue-api-query#48]
Maybe I misunderstand something, but I get `Can not use keyword 'await' outside an async function` error when using this code (I am using it inside a quasar-framework installation):

## Page.vue
```js
....
import Project from '../../models/Project'

export default {
  mounted() {
    let project = await Project.find(1);
  }
}
...
```

## models/Model.js
```js
import { Model as BaseModel } from 'vue-api-query'

export default class Model extends BaseModel {

  // define a base url for a REST API
  baseURL () {
    return 'http://api.simplefin.local/v1'
  }

  // implement a default request method
  request (config) {
    return this.$http.request(config)
  }
}

```

## models/Project.js
```js
import Model from './Model'

export default class User extends Model {
  resource()
  {
    return 'users'
  }
}
```

## boot/model.js (similar to main.js)
```js
import { Model } from 'vue-api-query'
import axios from 'axios'

export default async ({ app, router, Vue }) => {
  Model.$http = axios
}
```

**Comment by robsontenorio** [comment]
This is about ES6 async/await. 

On “Page.vue” you missed “async mounted()”

**Comment by bernhardh** [comment]
Ah. Ok, thanks!

**Comment by bernhardh** [comment]
Sorry, for disturbing you again, but why is this not working (it logs the promise instead of the result):

```js
mounted() {
    let projects = this.getProjects(id)
    console.log(projects)
},
methods: {
    async getProjects(id) {
        return await Project.find(id)
    }
}
```

And just for my understanding - the following (working) examples do more or less the same, right?

```js
// Version 1
mounted() {
    Project.find(id).then(res => {
        console.log(projects)
    });
}

// Version 2
async mounted() {
    let project = Project.find(id)
    console.log(projects)
}
```

Both examples are logging the result as expected and not the promise.

**Comment by robsontenorio** [comment]
Like i said at previous comment, it is not a issue about `vue-api-query`. I recommend you take a look on ES6 `async/await` spec and `Promises`. In all your examples there a misunderstanding about placing async/await directives.
