### ISSUE TITLE
parameterNames is ignored

### ISSUE THREAD

**Issue by bernhardh** [robsontenorio/vue-api-query#49]
The method `parameterNames` mentioned in the readme is ignored. I want to change the params to json:api specification (for use with https://github.com/spatie/laravel-json-api-paginate) 

```js
import { Model as BaseModel } from 'vue-api-query'

export default class Model extends BaseModel {

  // define a base url for a REST API
  baseURL () {
    return this.$http.defaults.baseURL
  }

  // Overwrite parameter names because of json:api spec
  parameterNames () {
    return {
      include: 'include',
      filter: 'filter',
      sort: 'sort',
      fields: 'fields',
      append: 'append',
      page: 'page[number]',
      limit: 'page[size]'
    }
  }

  // implement a default request method
  request (config) {
    return this.$http.request(config)
  }
}
```

Tried to console.log inside `parameterNames` and it never gets called (`baseUrl` and `request` get called)

**Comment by robsontenorio** [comment]
@Peter-Krebs can you help?

**Comment by robsontenorio** [comment]
@bernhardh Just tested your use case. And it works as expected. Make sure you have updated the package to latest version. Currently 1.4.1

```
yarn add vue-api-query
```

**Comment by bernhardh** [comment]
Thank you. Now its working. With `1.3.x` it wasn't working.
