### ISSUE TITLE
select as

### ISSUE THREAD

**Issue by hubroot** [robsontenorio/vue-api-query#5]
May be if there's an option to do something like 
Model.select( [ 'id',  { 'title': 'name' } ] ).get() !

which is like select id, title as name from Model

But it's client side, the server returns name, and the client vue-api-query override with the given as attribute

**Comment by robsontenorio** [comment]
I understand your point of view. But, the proposed syntax does not make very clear the usage. You can achieve the expected effect by using the `map()` function from  ES6, right after the `get()` from vue-api-query.
