### ISSUE TITLE
baseURL in get() is missing when using custom() resource

### ISSUE THREAD

**Issue by peterquentin** [robsontenorio/vue-api-query#50]
https://github.com/robsontenorio/vue-api-query/blob/f9f4cec14158e1acbbb4c3435e024c32139b01a6/src/Model.js#L258

BaseURL must be different from your client url in order to see this issue.
example would be: 

- localhost:3000 for the client and 
- project.localhost/api as BaseURL for your API requests.

Suggested fix:
```
base = this._customResource ? `${this.baseURL()}/${this._customResource}` : base
```
I could submit a PR if this would help to solve this issue asap.
Also thank you for this amazingly easy to use package.

**Comment by robsontenorio** [comment]
Are you using Vue or Nuxt? On your axios global config do you have a `baseURL`?

**Comment by josegus** [comment]
would be useful if we could set an "customAbsoluteUrl" on execution time
