### ISSUE TITLE
Creating child to parent fails

### ISSUE THREAD

**Issue by prodigy7** [robsontenorio/vue-api-query#52]
In my project I fetch a record "mainRecord". That has a relation to "childRecords".

When I want create now a new childRecord with that,
```
      let childRecord = new this.mainRecord.childRecord({
        val: null,
        sequence: null
      });
      childRecord.save()
        .then(response => {
        })
        .catch(error => {
        });
```
it fails with:
```
Uncaught (in promise) TypeError: Cannot read property 'childRecord' of undefined
```
Whats wrong with my code? Fetching, updating and deleting of childRecords is working without any problem. Only creating fails, maybe because i am using the wrong syntax.

**Comment by robsontenorio** [comment]
As far as I know, that syntax does not work with ES6.

```
new this.mainRecord.childRecord
```

**Comment by prodigy7** [comment]
Ok. Any idea, how I can create a child record related to his parent? Another option would be, construction a workaround.

**Comment by robsontenorio** [comment]
That is not related to `vue-api-query`. But, in ES6 you can not call `new` in a chain. Maybe you can try  something like

```
let object = new this
let mainRecord = new MainRecord
object.mainRecord = mainRecord
```
and so on...

**Comment by prodigy7** [comment]
It's okay if you don't want to teach me how to use JavaScript correctly, I have to teach myself ;-)
But somehow i'm not sure it isn't maybe a wrong behaviour from vue-api-query currently. When I do
```
      let childValues= {
        val: 'test1',
        sequence: 'test2'
      };
      await this.mainRecord
        .childRecord(childValues)
        .save()
        .then(response => {
...
        });
```
(which I think is the right syntax) I get a exception
```
Uncaught (in promise) TypeError: Converting circular structure to JSON
```
When I inspect the error, it is thrown in the axios library in the transformRequest method, line 50 (lib/defaults.js) by stringify method.
```
    if (utils.isObject(data)) {
      setContentTypeIfUnset(headers, 'application/json;charset=utf-8');
      return JSON.stringify(data);
    }
```
Inspecting with chrome shows me, the content of data is ``childRecord {_builder: Builder)`` which looks to me its wrong. When I do a call with existing data, i see a json like formatted content. Same when I create directly a mainChild: data contains json.

In my sample on the top I would expect, data contains
```
      {
        val: 'test1',
        sequence: 'test2'
      }
```
but it isn't so somehow the given data is passed wrong.

My defined models:
_MainRecord.js_
```
import Model from '../../../Model'
import ChildRecord from './ChildRecord';

export default class Type extends Model {
    primaryKey() {
        return 'Id';
    }

    resource() {
        return 'mainRecord'
    }

    ChildRecord() {
        return this.hasMany(TypeValueList)
    }
}
```

_ChildRecord.js_
```
import Model from '../../../Model'

export default class Type extends Model {
    primaryKey() {
        return 'Id';
    }

    resource() {
        return 'childRecord'
    }
}
```
