### ISSUE TITLE
Pass Model to asyncData of nuxt

### ISSUE THREAD

**Issue by pikock** [robsontenorio/vue-api-query#57]
I try to pass a Model to asyncData nuxt and pass it as props to a component.
In the component, I can't access to category.$save(). It seems that Nuxt is remove $https function of the Model. How can we do that?
 
```js 
<component :category="category"/>
data() {
    return {
      category: {},
      }
  },
async asyncData({ params}) {
    const category = await Category.find(params.id)
    return { category }
  }
```

**Comment by robsontenorio** [comment]
Is `find()` working with asyncData?

I can’t see `save()` on your example.

**Comment by pikock** [comment]
Yes, find() is working, it'd get a Resource but when Nuxt merge it with the data, it
remove $http function such as save.

Here is the example code in the component children where we do save.

```js 

<component :category="category"/>
props: {
    category: {
      type: Object,
      required: true
    }
  },
methods: {
    async submit() {
       await this.category.save()
    }
  }
```
So for now, I gotta call the data in **async created in order to work but was wondering if you know a better way with nuxt**.

```js 

<component :category="category"/>
data() {
    return {
      category: {},
      }
  },
async created() {
    this.category = await Category.find(this.$route.params.id)
  }
```

**Comment by robsontenorio** [comment]
I suppose the second snippet really is the right approach.

**Comment by xibman** [comment]
Yes but not if you need SSR

**Comment by xibman** [comment]
I think i found the way to fix it : https://github.com/vuex-orm/vuex-orm/commit/ac680c5ece50c473b59a8b64087197613be18526#diff-5e1a192a8d13cb82ce1d1c7d9f11142d

**Comment by robsontenorio** [comment]
Didn’t tried Nuxt with SSR. But, if you can submit a PR , with tests would be nice.
