### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by alaxfilho** [robsontenorio/vue-api-query#58]
Hi, first of all, congratulations on the api.
I have a problem in the first test, it is generating without errors but when I execute the method below the error in the line of the message GET: [Vue Warn: Error in v-on handler: "TypeError: Can not read property 'get' of undefined"

 methods: {
    GetMunicipio() {
      let municipios;
      municipios
        .get()
        .then((response) => {
          municipios = response;
        });
      console.log(municipios.nome);
    },

**Comment by robsontenorio** [comment]
Please, keep English as main language. Edit your comment, so more people can help you.

**Comment by Peter-Krebs** [comment]
`municipios` is not a Model, so there is nothing to `get()`.
By writing `let municipios;` you just create an undefined variable.

It should be something like `let municipios = new Municipio();`, assuming Municipio is a Vue-Api-Query model.

Follow the readme to define your model:  
https://github.com/robsontenorio/vue-api-query#configuration

**Comment by robsontenorio** [comment]
Or just import Municipio model and call any available methods like get(), find() ...

**Comment by kissu** [comment]
> It should be something like `let municipios = new Municipio();`, assuming Municipio is a Vue-Api-Query model.

Not sure how to do that one. Could you give me an example on this one please ? 😄 
PS: it's working as a basic import.

**Comment by Peter-Krebs** [comment]
Again, `municipios` from your code above does not have a type, it is an uninitialized variable. You are calling `get()` on it, which will not work on an undefined value.  
Therefore you have to initialize the value as a vue-api-query model first.

You replace `let municipios;` from your code with `let municipios = new Municipio();`.  
This should work.


*Documentation:*

My documentation link from above is outdated. You can find it here now:  
https://robsontenorio.github.io/vue-api-query/configuration

You then follow the examples from "Building the query".  
https://robsontenorio.github.io/vue-api-query/building-the-query
