### ISSUE TITLE
Use nested functions conditionally

### ISSUE THREAD

**Issue by rossity** [robsontenorio/vue-api-query#60]
HI,

In short, I'd like to be able to do the following:

```javascript
// GET /posts/{id_post}/comments

let comments = await this.post.comments().get()

// Pick any comment from list and edit it

let comment = comments[0]
comment.text = 'Changed!'

// PUT /comments/{id_comment}

await comment.save() 

// DELETE /comments/{id_comment}

await comment.delete() 
```

and 

```javascript
 let post = new Post({title: 'Woo!'})  

 // POST /posts
 await post.save()

// POST /posts/{id_post}/comments

let comment = new Comment({text: 'New one for this post'}).for(post)

comment.text = 'Changed!'

// PUT /comments/{id_comment}

await comment.save() 

// DELETE /comments/{id_comment}

await comment.delete() 
```

Basically I want to use nested relationships _only_ for the `get` and `post` actions, and the base route for `find`, `update`, and `delete`.

The reason for this is because nested routes aren't necessary if you already have the unique ID of the model you want to interact with.

Is there any way to easily override this on all models? It seems like I'd have to re-write quite a bit but maybe I'm missing something!

Right now it doesn't seem possible as once the model is related it keeps the same endpoint.

**Comment by robsontenorio** [comment]
Once you use `for()` method you are relying on nested relationships. 

```js
let comment = new Comment({text: 'New one for this post'}).for(post)
```

You can try to use a fresh new instance from child model instead.

```js
let comment = new Comment({text: 'New one for this post'})
```

**Comment by Peter-Krebs** [comment]
@rossity Was the workaround provided satisfactory? I believe we can close this.

You are correct the model keeps the same endpoint. It would be some rework currently. If you want to provide a PR we can talk about it.
