### ISSUE TITLE
when where item is null

### ISSUE THREAD

**Issue by ngkarkeong** [robsontenorio/vue-api-query#62]
when  this.executeAfter,  this.executeBefore,  this.description are Null.
let schedule = await CampaignSchedule
                    .where('execute_after', this.executeAfter)
                    .where('execute_before', this.executeBefore)
                    .where('description', this.description)
                    .get()
this will generate a request as so
/campaign_schedule?filter[execute_after]=&filter[execute_before]=&filter[description]=

my situation will prefer to have such request, instead.
/campaign_schedule

the reason is filtering with arguments of nothing basically mean without filters.

the question is, is there a clean way to ignore the 'Where' filter, while the filter is Null or undefine (similar to how Axios implement params )?

thanks in advance

**Comment by robsontenorio** [comment]
Sorry, but we cant have both implementations/behaviors. 

At this time, the chosen strategy is: a empty variable will always be generated if you call `where()` with null values. So, you must handle it on backend.
