### ISSUE TITLE
how to use custom method in dynamic address?

### ISSUE THREAD

**Issue by GronkOut** [robsontenorio/vue-api-query#63]
Thank you for making a good module.
I have a question.

It is a dynamic address set in several words.
`/post/category-a`, `/post/category-b`, `/post/category-c`...

'get()' was implemented using 'custom()'.
```javascript
// GET /api/post/category-a
Post.custom(`/api/post/${categoryCode}`).get();
```
**success**

But, how do I 'save', 'delete', 'edit'?
```javascript
// POST /api/post/category-a
const post = await Post.custom(`/api/post/${categoryCode}`).get();
post.title = 'text'
post.save();

// DELETE /api/post/category-a

// PUT /api/post/category-a
```
**is not working..**

Is there a solution?

**Comment by Peter-Krebs** [comment]
Custom URLs for saving is done by calling `for()`. Read up about it in the readme.
`for()` can take multiple arguments to build the URL, preferably models. But you can also supply a single string.

**Comment by robsontenorio** [comment]
The `custom()` method was designed to be read only, so you wont have `save()` for it. This `custom()` should be used in the last case.  Whenever possible try to maintain the consistency of the endpoints at backend. You can try the solution pointed by @Peter-Krebs

**Comment by Jacq** [comment]
> Custom URLs for saving is done by calling `for()`. Read up about it in the readme.
> `for()` can take multiple arguments to build the URL, preferably models. But you can also supply a single string.

In the current version it only accepts a valid Model not a string, is this correct?

**Comment by Peter-Krebs** [comment]
Ah yes that is correct. `custom()` can take strings, but not `for()`.  
When saving and updating you must send the request to a valid API resource. Your API resources must currently be organized as models to make that the most RESTful.
