### ISSUE TITLE
How can I pass baseUrl from vuex

### ISSUE THREAD

**Issue by koekaverna** [robsontenorio/vue-api-query#64]
I have a base Model.js, how can I access store from it?

```
import { Model as BaseModel } from 'vue-api-query'

export default class Model extends BaseModel {
  // define a base url for a REST API
  baseURL () {
    const team = ''// TODO: get this from vuex store
    return `${process.env.apiUrl}/teams/${team}`
  }

  // implement a default request method
  request (config) {
    return this.$http.request(config)
  }

  async restore() {
    await this.sync({ deleted: false })
  }
}
```

I'm using nuxt.

API routes look like this:
```
/api/teams/{uuid}/products
/api/teams/{uuid}/products/{id}
/api/teams/{uuid}/comments
/api/teams/{uuid}/comments/{id}
```

**Comment by robsontenorio** [comment]
Your `Model.js` is a ES6 class. So, this a ES6 stuff like: how to get VUEX instance into standalone ES6 class. Not related to `vue-api-query` at all.

Just like `$axios` instance as described on readme...

```js
import axios from 'axios'
import { Model } from 'vue-api-query'

// inject global axios instance as http client to Model
Model.$http = axios
```

You can try to pass a VUEX instance into your `Model.js` using same approach. At this moment, don't know if it is the best practice.

**Comment by koekaverna** [comment]
Thank you!

This code work for me:
```
import { Model } from 'vue-api-query'
import axios from 'axios'

export default ({ store }) => {
  axios.defaults.storeGetters = store.getters
  Model.$http = axios
}
```

But it's not clear for me, why when I use `Model.$storeGetters = store.getters` in my Model `this.$storeGetters` is `null`
But `Model.$http = store.getters` pass the parameter.

**Comment by robsontenorio** [comment]
@koekaverna 

`Model.$http = axios` was a sample. You should to try with a new var like `Model.$store = store`
