### ISSUE TITLE
updating the object sends a POST request

### ISSUE THREAD

**Issue by abishekrsrikaanth** [robsontenorio/vue-api-query#65]
Here is the code I have that I am using to update and I can get the save/update to work?

```
this.productObj = await Product.include('variants', 'additional_info', 'nutrition_fact')
                .append('min_priced_variant')
                .find(this.productId)

this.productObj.name = 'Test';
this.productObj.category_id = 3;

this.productObj.save();
```

Is there any reason why this would send a POST request to `/products` instead of a PUT request to `/products/{id}`.

Am I missing something?

**Comment by robsontenorio** [comment]
Make sure wrapper method has “async” keyword.

**Comment by Peter-Krebs** [comment]
If `id` is the primary key, it should POST and PUT correctly.  
You can override the primary key with `primaryKey()` in your model (see docs), if that's the issue.

**Comment by robsontenorio** [comment]
@abishekrsrikaanth Make sure to check suggestion pointed by @Peter-Krebs as well.

**Comment by abishekrsrikaanth** [comment]
@robsontenorio , I have the async wrapper on the method and so is the `primaryKey()` on the model as mentioned on the docs. The only way it works is if I set the id on the object before I call the save method.

```
this.productObj.id = 1;

this.productObj.name = 'Test';
this.productObj.category_id = 3;

this.productObj.save();
```

**Comment by robsontenorio** [comment]
Please, can you share `models/Product.js`  and `<script>` block from  `.vue` file as well?

**Comment by Smbat141** [comment]
I have the same problem, here is my code
 async editUser(user_id) {
                let user = await User.find(user_id);
                user.User.id = user_id;
                user.User.last_name = 'name';
                user.save();
}

**Comment by Peter-Krebs** [comment]
@Smbat141 `user.User.last_name` seems unusual to me. Try `user.last_name` instead.
PS: Please format your code

**Comment by Peter-Krebs** [comment]
@Smbat141 Did my suggestion find the error?  
I'm guessting this can be closed?

**Comment by robsontenorio** [comment]
Nice, please DM on twitter @robsontenorio

**Comment by francoism90** [comment]
Just for the record this also happens to me. I'm retrieving the model as in `{ data: {...}, meta: {...} }`, so be aware this doesn't include the id in the request.
