### ISSUE TITLE
Params method not worked in Nuxt.js at SSR mode

### ISSUE THREAD

**Issue by hamid-ne** [robsontenorio/vue-api-query#69]
in my Nuxt.js Application params method not worked at SSR(Server Side Render) mode.

in client side render work perfectly 

<img width="1680" alt="Screen Shot 1398-02-21 at 8 51 45 AM" src="https://user-images.githubusercontent.com/31789477/57564969-11c19c80-73ca-11e9-828b-b85377fa03b3.png">

**Comment by bazel** [comment]
same here. Did you find a  solution? Thanks

**Comment by robsontenorio** [comment]
@hamid-ne @bazel 

Are you `params.slug` return a proper string?

You can give a try by using a dummy payload to test it.

```
await Page.params({foo: 'bar'}).get()
```

No erros should be throw.

**Comment by lasthead** [comment]
`page = new pageObject({ code: params.brand, show_all: 'y' })
page.get()
`
that work for me

**Comment by suth** [comment]
Same issue here, dummy payload will cause the same error with SSR. Found this solution here but I'm gonna look into alternative solutions when I have the time https://github.com/nuxt/nuxt.js/issues/7266#issuecomment-638382133
