### ISSUE TITLE
The where method operator is it possible? 

### ISSUE THREAD

**Issue by zhi8617** [robsontenorio/vue-api-query#7]
like 
`where (key, operator ,value) `
`where('status','>' ,1)`

Thank.

**Comment by robsontenorio** [comment]
An interesting answer from another related package: 

"I agree that these kind of filters are something you'll be doing often. However my only concern is that this is not part of the JSON API spec. As everyone seems to use different approaches to this kind of filtering." (@AlexVanderbist)

So, For now, i recommend you to use some custom filters on backend.
