### ISSUE TITLE
Model throw Warn in Nuxt

### ISSUE THREAD

**Issue by gaelreyrol** [robsontenorio/vue-api-query#71]
Hi,

The model returned when a response request is parsed throw a warn in Nuxt.
```
 Cannot stringify arbitrary non-POJOs ...
```
Nuxt tries to [devalue](https://github.com/nuxt/devalue) the object but does not have the same `prototype` as an `Object`.

It is clearly declared [here](https://github.com/nuxt/devalue/blob/master/src/index.ts#L71).

Regards

**Comment by njxqlus** [comment]
Same

**Comment by robsontenorio** [comment]
Please, consider updating your Nuxt version.
If problem persists, please open a new issue with more details and code sample.

**Comment by rdpascua** [comment]
Installed the latest nuxt just now, I'm having the same issue

**Comment by robsontenorio** [comment]
@rdpascua Please, open a new issue with a repo.
