### ISSUE TITLE
Catching Errors on model.save()

### ISSUE THREAD

**Issue by Tes3awy** [robsontenorio/vue-api-query#73]
Hello,

I am trying to catch error on POST data.

My code:

```vue
<form
          @submit.prevent="onSubmit"
          class="apply-form-section__form"
          action
          method="POST"
          ref="form"
          role="form"
        >
          <div class="apply-form-section__input-wrapper">
            <input
              type="text"
              class="apply-form-section__input-wrapper--input-field"
              placeholder="Name"
              v-model.lazy.trim="formResponses.name"
            >
          </div>
          <div class="apply-form-section__input-wrapper">
            <input
              type="tel"
              class="apply-form-section__input-wrapper--input-field"
              placeholder="Phone number"
              v-model.lazy.trim="formResponses.mobile"
            >
          </div>
          <div class="apply-form-section__input-wrapper">
            <input
              type="text"
              class="apply-form-section__input-wrapper--input-field"
              placeholder="Company"
              v-model.lazy.trim="formResponses.company"
            >
          </div>
</form>
```

```js
data() {
      return {
        formResponses: {
          name: "",
          mobile: "",
          company: "",
          position: "",
          email: ""
        },
      };
    },
methods: {
      async onSubmit() {
        console.log("form responses:", this.formResponses);
        let newApplication = new CardApplication({
          name: this.formResponses.name,
          mobile_phone: this.formResponses.mobile,
          company: this.formResponses.company,
          position: this.formResponses.position,
          email: this.formResponses.email
        });

        await newApplication
          .save()
          .then(response => {
            this.formSubmitted = true;
            if(response.meta.code == 200) {
              console.log("success:", response);
              console.log("form data:", this.formResponses);
            }
          })
          .catch(err => {
            console.log("ERROR SAVING APPLICATION:", err);
          });
      }
```

The problem is that I don't get the supposed response object on error. I only get `Error: Request failed with status code 400` in the console.

Can you help me with this?

**Comment by Dylan-Chapman** [comment]
I do the following within my base model that all of my other models extend (class Model extends VueApiQueryBaseModel):

```js
async save() {
	try {
		return await super.save();
	} catch ( e ) {
		// Stuff I want to do on fail
	} finally {
		// Stuff I want to do regardless of success/fail
	}
}
```

**Comment by Peter-Krebs** [comment]
Can you test the response of your backend with a tool like _Postman_ or _wget_?
If your backend doesn't respond with a JSON object, the `catch(err)` will probably only have the plain text message, is my guess.

* Create a breakpoint on the console.log line to find out which type `err` is or add another line `console.log(typeof err)`
* Maybe your frontend error handling could have a `switch(typeof err)` which handles both a plain error message as well a JSON formatted error response?
* Check if your environment is in production mode - in this case you won't get a stacktrace of the error, but must check laravel's logfiles

If the type is `string` your backend is probably also answering with a string.  
Maybe the cause for the `HTTP 400` sends your backend into such a problem that the response is not a JSON object. Make sure the backend is returning a `Response::json` call, even in case of an error.

**Comment by Tes3awy** [comment]
@Peter-Krebs Thank you for your detailed answer. I tested the response on Postman before creating the issue. I get the response from the backend as an object as it supposed to _(See screenshot below)_. But in the browser. It just console.log an error, not the object. However; in the success case, I get the supposed response which is also an object.

![Screenshot_2019-06-18_10-38-09](https://user-images.githubusercontent.com/11368432/59666542-4be64100-91b5-11e9-9fcb-a642c1ad2278.png)

I created the breakpoint as you suggested and I figured out the error type is an object which is correct, but is not displayed on console.log in the browser. _(See screenshot below)_
As you can see, the error type is an object, but the error displayed error is just a string!

![Screenshot_2019-06-18_10-46-21](https://user-images.githubusercontent.com/11368432/59667349-e1360500-91b6-11e9-868c-c5bd117c1e7c.png)

Your second and third speculations were covered but still have the same issue.

**Comment by Peter-Krebs** [comment]
Okay great, the response is an object then. Your screenshot shows `object`.
So if you successfully get an object, why stop there?
Add an empty array of errors to your `data` and loop through them in your template.

```js
// ...
.catch(err => {
  this.errors = err.meta.errors;
});
```

**Comment by Tes3awy** [comment]
@Peter-Krebs I already tried what you suggested, but it isn't working. After setting 
```js
this.errors = err.meta.errors
```
,and trying `console.log`, I get this error:

![Screenshot_2019-06-18_18-10-06](https://user-images.githubusercontent.com/11368432/59700754-570c9180-91f4-11e9-991a-357bff99a0ec.png)

**Comment by Peter-Krebs** [comment]
I believe the response is wrapped again by Axios.  
Create a breakpoint again to find out which variable it puts the response in. It might be `err.response.meta.errors`, `err.data.meta.errors` or something similar.

**Comment by Tes3awy** [comment]
@Peter-Krebs No sir, still not working. The response is correct but it's not even displayed to the console. I can't get the response object itself. I know it says object when `console.log(typeof error)`. But it still can't parse the object itself.

**Comment by Peter-Krebs** [comment]
@Tes3awy Well if your code gets to the `catch(err)` part and the response is an object it already means it is working. The rest is up to your application.

I'm obviously just guessing available object properties, they are sometimes application specific. This is not an issue with vue-api-query. Axios and vue-api-query sometimes add their own properties depending on the request.

So what is keeping you from looking up the object's properties?

* Create a breakpoint, mouse over the object and expand the available properties
* Why not `for(var prop in err) { console.log(err[prop]); }` also?

**Comment by Tes3awy** [comment]
@Peter-Krebs Finally, I was able to get the error object from `err.response.data.meta.errors`. Thanks a lot for your help. I figured out the solution from this issue on axios repository [#960](https://github.com/axios/axios/issues/960#issuecomment-309287911)
