### ISSUE TITLE
Transforming Relations to their models

### ISSUE THREAD

**Issue by saeidee** [robsontenorio/vue-api-query#74]
Thanks for the nice package!
Is there any way to change convert relations object to their model type!
for example, comment has many replies but when we including replies it is just giving comment as model and replies are still plain objects which in fact they should transform to their models! 
![Screenshot from 2019-06-13 15-14-14](https://user-images.githubusercontent.com/29974712/59431599-f5ac8300-8ded-11e9-8903-90919c0ec757.png)

**Comment by Dylan-Chapman** [comment]
Just wanted to post my personal workaround for this. It could probably be re-written to be a bit tidier, but I wrote it quite a while back and never had any issues. Everything stated is within my base model that all of my other models extend (`class Model extends VueApiQueryBaseModel`).

Ultimately, this setup allows you to do the following in your models:
```js
export default class Comment extends Model {
	get mutations() {
		return {
			replies: MyRepliesModel
		};
	}
}
```

First, I have an `applyMutations` method that recursively transforms your object properties to the related models from their respective `mutations` getters:
```js
applyMutations( model ) {
	Object.keys( model.mutations || {} ).forEach( propKey => {
		if ( !model[propKey] ) {
			return;
		}

		const ModelForKey = model.mutations[propKey];

		if ( Array.isArray( model[propKey] ) ) {
			model[propKey].forEach( ( item, i ) => {
				const modelData = model[propKey][i];

				model[propKey][i] = new ModelForKey( modelData );

				this.applyMutations( model[propKey][i] );
			} );
		} else {
			const modelData = model[propKey];

			model[propKey] = new ModelForKey( modelData );

			this.applyMutations( model[propKey] );
		}
	} );
}
```

Then I extend the default methods, such as `find`, `get`, and `save` to make sure the mutations are applied when the model is fetched:
```js
async save() {
	return await super.save().then( model => {
		this.applyMutations( model );

		return model;
	} );
}

async find( id ) {
	return await super.find( id ).then( model => {
		this.applyMutations( model );

		return model;
	} );
}

async get() {
	return await super.get().then( models => {
		models.forEach( model => {
			this.applyMutations( model );
		} );

		return models;
	} );
}
```

And that should do it!
