### ISSUE TITLE
Is there a way that I can do a custom post?

### ISSUE THREAD

**Issue by denjaland** [robsontenorio/vue-api-query#75]
Hi,

I have a resource `Notification` on which I have some post methods available such as `POST /api/notifications/markallread` which basically marks all as read.

I was hopeing I could do something like `Notification.custom('markallread').post()` but as far as I can tell, only GET is supported, correct?

**Comment by Peter-Krebs** [comment]
This should be valid:
```javascript
new Notification({id: 'markallread'}).save();
```

When using deeper URLs check out `for()` in the readme.

**Comment by denjaland** [comment]
Okay.  I feel that's a bit of a workaround, as you are basically _creating a notification with a non-existing id_, but it would work.  I have another use case though that I don't see the solution for...

Let's say I have a Model invites (people can be invited to join another team).  and an invite can either be declined or accepted by the user.

My model is set up with resource `/me/invites`
So getting the pending invites works perfect with `Invite.get()`

Now, I want to be able to do `POST /me/invites/{id}/accept` and `POST /me/invites/{id}/decline` for accepting or declining an invitation.  I believe this is good REST principle.

I'm not sure how I can do this with this package though.

invite.save() does do a `POST /me/invites/{id}`but how can I customise that and add the accept/decline bit at the end of the route?  theoretically, I think I can get there by defining a new relation, but would it not be overkill to having to create two models for InviteAccept / InviteReject only for this purpose?

I think I'm overlooking something here, so any feedback is much welcomed!

**Comment by Peter-Krebs** [comment]
You can use paramters instead, requests should go to the resource you are requesting.
`POST /api/notifications?markallread=1`

For your second use-case:
`POST /me/invites/{id}?accept=1`  
This would be more RESTful, because you are modifying an invite. "accept" or "decline" or not resources.

Sorry for the late reply, I was on vacation for a while :)

**Comment by Peter-Krebs** [comment]
@robsontenorio I believe this can be closed.

**Comment by reefki** [comment]
@Peter-Krebs any code example for this? I've tried with this:

```
const invite = await Invite.first()

invite.params({accept: 1}).save()
```

 but give me this error:

```
[Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'params' of undefined"
```

**Comment by Peter-Krebs** [comment]
@reefki Don't use `first()` for saving, it is intended for GET requests AFAIK.

You can try this ...:
```javascript
await new Invite().params({accept: 1}).save()
```

... or supply parameters to the constructor directly:
```javascript
await new Invite({accept: 1}).save()
```
