### ISSUE TITLE
Attach headers

### ISSUE THREAD

**Issue by retrogradeMT** [robsontenorio/vue-api-query#79]
How can I attach a header to a model?  
I am trying to add a response type like this: 

    axios({
    url: '.../static/example.pdf',
    method: 'GET',
     responseType: 'blob', // important
     }).then((response) => {}

**Comment by Peter-Krebs** [comment]
I'm thinking using a header like this would end up not making your API RESTful, since you cannot tell by the URL what the response will give you.  
I would rather use `.params()` for this, like `.params({'responseType': 'blob'})`.

**Comment by Peter-Krebs** [comment]
@retrogradeMT Did the reply above help resolve the issue?

**Comment by Peter-Krebs** [comment]
Closed due to inactivity.
