### ISSUE TITLE
Find with includes

### ISSUE THREAD

**Issue by PrimozRome** [robsontenorio/vue-api-query#84]
I wonder why `.include()` function does not work together with `.find()` method?

**Comment by Peter-Krebs** [comment]
Example code would help.

You have probably something like `await Post.find(4).include('comments')`?  
If yes, try the `.include()` first (`await Post.include('comments').find(4)`), as `.find()` is the function that sends the request.  
Treat it like you would `get()` - call it last.

**Comment by Peter-Krebs** [comment]
@PrimozRome Did the suggestion above help you?

**Comment by Peter-Krebs** [comment]
Closed for inactivity

**Comment by PrimozRome** [comment]
@Peter-Krebs sorry for the late response. Yes, your answer helped, thanks for that!
