### ISSUE TITLE
id param undefined when using relationships

### ISSUE THREAD

**Issue by BarryJamez** [robsontenorio/vue-api-query#85]
I have been troubleshooting an issue right of the box with this package - not sure what the cause could be..

When I follow the documentation step by step and use a simple relationship - the get request shows the id portion of the parent model on the request to be undefined.

Also, my VS Code suggests a TypeScript error - even though I'm not using TypeScript - not sure if this is related...
``Could not find a declaration file for module 'vue-api-query'. 'c:/Users/Mainframe/WebRoyal/Sites/BPM/Front End/sixbpm/node_modules/vue-api-query/build/index.js' implicitly has an 'any' type.
  Try `npm install @types/vue-api-query` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-api-query';`ts(7016)``

Anyone else experience this issue before?

Sorry! Some meta:

Using Nuxt @ 2^
Using Separate backend running Laravel - which returns the model with the id as a string (set the id to the slug in the resource) i.e. the server returns an 'id' column with a single word.

Error in console:
```GET http://xxx.test/api/schemes/undefined/tasks 404 (Not Found)

File structure is verbatim per the docs

**Comment by Peter-Krebs** [comment]
Please share your code for the request and the models.

The TypeScript error wouldn't happen if TypeScript wasn't configured (somewhere, somehow).  
Does the error happen if you create a fresh project with just vue and vue-api-query in it?

non-numeric id parameters should be supported. The base model checks using `isValidId()`:
```javascript
isValidId(id) {
  return id !== undefined && id !== 0 && id !== ''
}
```

The error message has probably nothing to do with vue-api-query. I don't have any experience using Nuxt, however, so sorry I don't have any pointers for that.

**Comment by Peter-Krebs** [comment]
@BarryJamez Have you resolved the issue? Can we close this?

**Comment by robsontenorio** [comment]
This package is not typed (typescript support).

`Could not find a declaration file for module 'vue-api-query'`

Please, consider reviewing your project setup.
