### ISSUE TITLE
.for() id error after save() new with "data" wrapper response

### ISSUE THREAD

**Issue by bpuig** [robsontenorio/vue-api-query#90]
Hello, I've found an issue with creating a new resource and then a relationship resource for such. This is a function in a vuex store, but I think that won't make any difference. The issue comes only when creating `new`, when updating there is no issue (I guess because object's `id` is already loaded from data wrapper with `$find`). This is my function:
```
async updateRole ({ dispatch }, payload) {
    let role
    if (payload.role.id !== '') {
      role = await Role
        .$find(payload.role.id)
    } else {
      role = new Role({})
    }

    role.name = payload.role.name

    await role.save()
      .then(async () => {
        let permissions = await new Permission({ permissions: payload.permissions }).for(role)
        permissions.save()
          .then(() => {
            dispatch('fetchRoles')
          })
      })
  }, 
```
Error returned is `The object referenced on for() method has a invalid id.`, seems that `save()` cannot process object wrapped in "data".
JSON response payload when creating role:
`{"data":{"id":12,"name":"fsfdsd","guardName":"api","createdAt":"2019-11-10T16:00:04.000000Z","updatedAt":"2019-11-10T16:00:04.000000Z"}}`

Maybe there is a need for` $save()` ? Am I doing something wrong?

**Comment by bpuig** [comment]
If you'd like to get an idea of where the issue is, this works, tests are passed: d0a24684c84185d0e66f28c07e82f219757436be

I'm not a professional programmer, but at least I tried :stuck_out_tongue_closed_eyes:

**Comment by Peter-Krebs** [comment]
I get your approach, thanks for sharing!  
The issue might be that the `role` object is not updated immediately on `.save()`.

You initialize a fresh `role` object here:  
```javascript
else {
  role = new Role({})
}
```

The `role` object is not updating itself, you should update it with `role.save().then()`'s response parameter:  
```javascript
await role.save()
  .then(async ( response ) => {
    role = response;
    // now continue using "role".
  })
```

It seems your provided commit for `$_create()` does the `role = response` part.  
I would stick with the suggestion above for performance reasons, because you might not always need the updated object (it takes time to loop through all properties and reassign them for you).

Assigning the variable again is also the way the current readme does it (look at `vue-api-query`'s readme and Ctrl+F for `user = response` you will find the spot).

**Comment by Peter-Krebs** [comment]
I'm assuming we can close this @bpuig ?

**Comment by bpuig** [comment]
Sure :)

**Comment by bpuig** [comment]
I said it was OK, but now I've returned to revise the code and I see it does not work. I think I left it since I was not using it.

With  `role = response` I get `Error: The object referenced on for() method has a invalid id`
I've tried with `role = response.data` I get `Error: The object referenced on for() method is not a valid Model. `

It only happens when I create a new Role, update works without issue.

**Comment by Peter-Krebs** [comment]
Can you print the whole `response` object? Maybe the API is not responding what (I think) it should.
I'm definitely using this pattern myself.

I have a list of tasks in an app. I save the task like this:

```javascript
new Task(this.task)
  .save()
  .then(task => {
    this.task = task;
  });
```

**Comment by Peter-Krebs** [comment]
@bpuig Do you need further help with this or can this issue be closed again? Thanks.

**Comment by bpuig** [comment]
I have a love/hate relationship with this…
Let's close it and hope I don't come back with the same 😓
