### ISSUE TITLE
This model has a empty ID

### ISSUE THREAD

**Issue by raghuv9** [robsontenorio/vue-api-query#94]
Hello
 **I'm trying to delete a record from db ,here is my code** 

import Post from './models/MailList ';

function to delete(id)
{
let post = await MailList .find(id)
//if i do console.log(post) i'm able to see the fetched record in the browser console
//while trying to delete it like this
await post.delete()
}
i'm getting an error saying This model has a empty ID.

Inside MailList model
-----------------------
import Model from './Model'
export default class MailList extends Model {
    resource() {
        return 'mail-list';
    }
}

My Api end point for delete request looks like this => http://demoapp.test/api/demo/mail-list/2

**here i'm attaching the ss of error**
![Screenshot_56](https://user-images.githubusercontent.com/26516842/73090770-fe764300-3efe-11ea-9967-4b9a56276657.png)

**Comment by Peter-Krebs** [comment]
Empty IDs are checked reasonably, so the error is probably correct:  
```javascript
isValidId(id) {
  return id !== undefined && id !== 0 && id !== ''
}
```

Can you share code of the models?

 Note that you can override the name of the primary key if it is not `id`, see readme.

**Comment by Peter-Krebs** [comment]
@raghuv9 Has this been resolved for you, can we close this issue?
