### ISSUE TITLE
No BaseUrl

### ISSUE THREAD

**Issue by Roywcm** [robsontenorio/vue-api-query#98]
I want to use ziggy routes inside my project from Laravel 
These routes will be absolute routes on each model, so I don't need the baseURL. 

When I do this, I get an error. 

```
baseURL () {
        return null
    }
```

How can I fix this?

**Comment by ariel0196** [comment]
Quick workaround:

```
baseURL() {
    return ""
 }
```

**Comment by Peter-Krebs** [comment]
@Roywcm Has @ariel0196 helped you with the suggestion?
Otherwise try `return "/"`, depending on your model's routes.

Can we close this?

**Comment by Roywcm** [comment]
Yes, I tried. Sometimes the request has a double ```https://``` prefixed, but i'm not sure why and if this is caused outside this package. I'll close it for now.
